import type { Source } from './types';

export const SOURCES: Source[] = [
  { id:'openai',name:'OpenAI',short:'OAI',color:'#10a37f',grad:'linear-gradient(135deg,rgb(4,32,19),rgb(1,13,7))',kind:'rss',url:'https://openai.com/news/rss.xml' },
  { id:'openai-blog',name:'OpenAI Blog',short:'OAI-B',color:'#10a37f',grad:'linear-gradient(135deg,rgb(4,32,19),rgb(1,13,7))',kind:'rss',url:'https://openai.com/blog/rss.xml' },
  { id:'googleai',name:'Google AI',short:'GAI',color:'#4285F4',grad:'linear-gradient(135deg,rgb(19,26,36),rgb(7,10,14))',kind:'rss',url:'https://blog.google/technology/ai/rss/' },
  { id:'googleresearch',name:'Google Research',short:'GR',color:'#34a853',grad:'linear-gradient(135deg,rgb(15,33,12),rgb(6,13,4))',kind:'rss',url:'https://research.google/blog/rss/' },
  { id:'deepmind',name:'Google DeepMind',short:'GDM',color:'#7c6cf0',grad:'linear-gradient(135deg,rgb(37,21,36),rgb(14,8,14))',kind:'rss',url:'https://deepmind.google/blog/rss.xml' },
  { id:'microsoft',name:'Microsoft AI',short:'MS',color:'#38bdf8',grad:'linear-gradient(135deg,rgb(16,37,37),rgb(6,15,14))',kind:'rss',url:'https://www.microsoft.com/en-us/ai/blog/feed/' },
  { id:'nvidia',name:'NVIDIA',short:'NV',color:'#76b900',grad:'linear-gradient(135deg,rgb(35,37,0),rgb(14,14,0))',kind:'rss',url:'https://blogs.nvidia.com/feed/' },
  { id:'nvidiadeveloper',name:'NVIDIA Developer',short:'NV-D',color:'#76b900',grad:'linear-gradient(135deg,rgb(35,37,0),rgb(14,14,0))',kind:'rss',url:'https://developer.nvidia.com/blog/feed/' },
  { id:'nvidia-robotics',name:'NVIDIA Robotics',short:'NV-R',color:'#76b900',grad:'linear-gradient(135deg,rgb(35,37,0),rgb(14,14,0))',kind:'rss',url:'https://developer.nvidia.com/blog/category/robotics/feed/' },
  { id:'apple',name:'Apple ML Research',short:'APL',color:'#a1a1aa',grad:'linear-gradient(135deg,rgb(48,32,25),rgb(19,12,10))',kind:'rss',url:'https://machinelearning.apple.com/rss.xml' },
  { id:'apple-newsroom',name:'Apple Newsroom',short:'APL-N',color:'#a1a1aa',grad:'linear-gradient(135deg,rgb(48,32,25),rgb(19,12,10))',kind:'rss',url:'https://www.apple.com/newsroom/rss-feed.rss' },
  { id:'amazon-ai',name:'AWS ML',short:'AWS',color:'#ff9900',grad:'linear-gradient(135deg,rgb(76,30,0),rgb(30,12,0))',kind:'rss',url:'https://aws.amazon.com/blogs/machine-learning/feed/' },
  { id:'aws-sagemaker',name:'AWS SageMaker',short:'AWS-S',color:'#ff9900',grad:'linear-gradient(135deg,rgb(76,30,0),rgb(30,12,0))',kind:'rss',url:'https://aws.amazon.com/blogs/machine-learning/tag/amazon-sagemaker/feed/' },
  { id:'aws-open-source',name:'AWS Open Source',short:'AWS-O',color:'#ff9900',grad:'linear-gradient(135deg,rgb(76,30,0),rgb(30,12,0))',kind:'rss',url:'https://aws.amazon.com/blogs/opensource/feed/' },
  { id:'salesforce',name:'Salesforce AI',short:'SF',color:'#00a1e0',grad:'linear-gradient(135deg,rgb(0,32,33),rgb(0,12,13))',kind:'rss',url:'https://www.salesforce.com/news/feed/' },
  { id:'mistral',name:'Mistral AI',short:'MIS',color:'#ff7000',grad:'linear-gradient(135deg,rgb(76,22,0),rgb(30,8,0))',kind:'rss',url:'https://mistral.ai/news/rss/' },
  { id:'cohere',name:'Cohere',short:'COH',color:'#39594D',grad:'linear-gradient(135deg,rgb(17,17,11),rgb(6,7,4))',kind:'rss',url:'https://cohere.com/blog/rss' },
  { id:'huggingface',name:'Hugging Face',short:'HF',color:'#ffd21e',grad:'linear-gradient(135deg,rgb(76,42,4),rgb(30,16,1))',kind:'rss',url:'https://huggingface.co/blog/feed.xml' },
  { id:'hf-papers',name:'HF Daily Papers',short:'HF-P',color:'#ffd21e',grad:'linear-gradient(135deg,rgb(76,42,4),rgb(30,16,1))',kind:'rss',url:'https://huggingface.co/blog/daily-papers/feed' },
  { id:'pytorch',name:'PyTorch',short:'PT',color:'#ee4c2c',grad:'linear-gradient(135deg,rgb(71,15,6),rgb(28,6,2))',kind:'rss',url:'https://pytorch.org/blog/feed.xml' },
  { id:'tensorflow',name:'TensorFlow',short:'TF',color:'#ff6f00',grad:'linear-gradient(135deg,rgb(76,22,0),rgb(30,8,0))',kind:'rss',url:'https://blog.tensorflow.org/feeds/posts/default/-/AI' },
  { id:'langchain',name:'LangChain',short:'LC',color:'#22c55e',grad:'linear-gradient(135deg,rgb(10,39,14),rgb(4,15,5))',kind:'rss',url:'https://blog.langchain.dev/rss/' },
  { id:'ollama',name:'Ollama',short:'OLL',color:'#ffffff',grad:'linear-gradient(135deg,rgb(76,51,38),rgb(30,20,15))',kind:'rss',url:'https://ollama.com/blog/rss.xml' },
  { id:'mlflow',name:'MLflow',short:'MLF',color:'#0194e2',grad:'linear-gradient(135deg,rgb(0,29,33),rgb(0,11,13))',kind:'rss',url:'https://mlflow.org/blog/rss.xml' },
  { id:'wandb',name:'Weights & Biases',short:'W&B',color:'#ffcc33',grad:'linear-gradient(135deg,rgb(76,40,7),rgb(30,16,3))',kind:'rss',url:'https://wandb.ai/fully-connected/rss.xml' },
  { id:'weaviate',name:'Weaviate',short:'WV',color:'#22c55e',grad:'linear-gradient(135deg,rgb(10,39,14),rgb(4,15,5))',kind:'rss',url:'https://www.weaviate.io/blog/rss.xml' },
  { id:'redis',name:'Redis AI',short:'RED',color:'#dc382d',grad:'linear-gradient(135deg,rgb(66,11,6),rgb(26,4,2))',kind:'rss',url:'https://redis.io/blog/feed/' },
  { id:'neo4j',name:'Neo4j',short:'N4J',color:'#018bff',grad:'linear-gradient(135deg,rgb(0,27,38),rgb(0,11,15))',kind:'rss',url:'https://neo4j.com/blog/feed/' },
  { id:'docker',name:'Docker',short:'DKR',color:'#2496ed',grad:'linear-gradient(135deg,rgb(10,30,35),rgb(4,12,14))',kind:'rss',url:'https://www.docker.com/blog/feed/' },
  { id:'dbt',name:'dbt Labs',short:'DBT',color:'#ff694b',grad:'linear-gradient(135deg,rgb(76,21,11),rgb(30,8,4))',kind:'rss',url:'https://www.getdbt.com/blog/feed.xml' },
  { id:'kubernetes',name:'Kubernetes',short:'K8S',color:'#326ce5',grad:'linear-gradient(135deg,rgb(15,21,34),rgb(6,8,13))',kind:'rss',url:'https://kubernetes.io/feed.xml' },
  { id:'terraform',name:'HashiCorp',short:'HC',color:'#7c3aed',grad:'linear-gradient(135deg,rgb(37,11,35),rgb(14,4,14))',kind:'rss',url:'https://www.hashicorp.com/blog/feed.xml' },
  { id:'helm',name:'Helm',short:'HELM',color:'#0f1689',grad:'linear-gradient(135deg,rgb(4,4,20),rgb(1,1,8))',kind:'rss',url:'https://helm.sh/blog/index.xml' },
  { id:'supabase',name:'Supabase',short:'SUP',color:'#3ecf8e',grad:'linear-gradient(135deg,rgb(18,41,21),rgb(7,16,8))',kind:'rss',url:'https://supabase.com/blog/rss.xml' },
  { id:'neon',name:'Neon',short:'NEO',color:'#00e599',grad:'linear-gradient(135deg,rgb(0,45,22),rgb(0,18,9))',kind:'rss',url:'https://neon.tech/blog/rss.xml' },
  { id:'prisma',name:'Prisma',short:'PRM',color:'#2d3748',grad:'linear-gradient(135deg,rgb(13,11,10),rgb(5,4,4))',kind:'rss',url:'https://www.prisma.io/blog/rss.xml' },
  { id:'svelte',name:'Svelte',short:'SVT',color:'#ff3e00',grad:'linear-gradient(135deg,rgb(76,12,0),rgb(30,4,0))',kind:'rss',url:'https://svelte.dev/blog/rss.xml' },
  { id:'remix',name:'Remix',short:'RMX',color:'#3992ff',grad:'linear-gradient(135deg,rgb(17,29,38),rgb(6,11,15))',kind:'rss',url:'https://remix.run/blog/rss.xml' },
  { id:'django',name:'Django',short:'DJO',color:'#092e20',grad:'linear-gradient(135deg,rgb(2,9,4),rgb(1,3,1))',kind:'rss',url:'https://www.djangoproject.com/rss/weblog/' },
  { id:'express',name:'Express',short:'EXP',color:'#000000',grad:'linear-gradient(135deg,rgb(0,0,0),rgb(0,0,0))',kind:'rss',url:'https://expressjs.com/feed.xml' },
  { id:'flutter',name:'Flutter',short:'FLT',color:'#02569B',grad:'linear-gradient(135deg,rgb(0,17,23),rgb(0,6,9))',kind:'rss',url:'https://medium.com/feed/flutter' },
  { id:'react-native',name:'React Native',short:'RN',color:'#61dafb',grad:'linear-gradient(135deg,rgb(29,43,37),rgb(11,17,15))',kind:'rss',url:'https://reactnative.dev/blog/feed.xml' },
  { id:'swift',name:'Swift',short:'SWFT',color:'#f05138',grad:'linear-gradient(135deg,rgb(72,16,8),rgb(28,6,3))',kind:'rss',url:'https://developer.apple.com/news/rss/news.rss' },
  { id:'azure-ai',name:'Azure AI',short:'AZ',color:'#0078d4',grad:'linear-gradient(135deg,rgb(0,24,31),rgb(0,9,12))',kind:'rss',url:'https://azure.microsoft.com/en-us/blog/feed/' },
  { id:'digitalocean',name:'DigitalOcean',short:'DO',color:'#0080ff',grad:'linear-gradient(135deg,rgb(0,25,38),rgb(0,10,15))',kind:'rss',url:'https://www.digitalocean.com/blog/rss' },
  { id:'digitalocean-tutorials',name:'DO Tutorials',short:'DO-T',color:'#0080ff',grad:'linear-gradient(135deg,rgb(0,25,38),rgb(0,10,15))',kind:'rss',url:'https://www.digitalocean.com/community/tutorials/feed' },
  { id:'linode',name:'Linode Blog',short:'LIN',color:'#00b050',grad:'linear-gradient(135deg,rgb(0,35,12),rgb(0,14,4))',kind:'rss',url:'https://www.linode.com/blog/feed/' },
  { id:'runpod',name:'RunPod',short:'RNP',color:'#22c55e',grad:'linear-gradient(135deg,rgb(10,39,14),rgb(4,15,5))',kind:'rss',url:'https://www.runpod.io/blog/rss.xml' },
  { id:'modal',name:'Modal',short:'MOD',color:'#6366f1',grad:'linear-gradient(135deg,rgb(29,20,36),rgb(11,8,14))',kind:'rss',url:'https://modal.com/blog/rss' },
  { id:'replicate',name:'Replicate',short:'REP',color:'#6366f1',grad:'linear-gradient(135deg,rgb(29,20,36),rgb(11,8,14))',kind:'rss',url:'https://replicate.com/blog/rss' },
  { id:'datarobot',name:'DataRobot',short:'DR',color:'#1c4e80',grad:'linear-gradient(135deg,rgb(8,15,19),rgb(3,6,7))',kind:'rss',url:'https://www.datarobot.com/blog/feed/' },
  { id:'alignmentforum',name:'Alignment Forum',short:'AF',color:'#f97316',grad:'linear-gradient(135deg,rgb(74,23,3),rgb(29,9,1))',kind:'rss',url:'https://www.alignmentforum.org/feed.xml' },
  { id:'lesswrong',name:'LessWrong',short:'LW',color:'#dc2626',grad:'linear-gradient(135deg,rgb(66,7,5),rgb(26,3,2))',kind:'rss',url:'https://www.lesswrong.com/feed.xml?feedType=recentCurated' },
  { id:'future-of-life',name:'Future of Life',short:'FLI',color:'#8b5cf6',grad:'linear-gradient(135deg,rgb(41,18,36),rgb(16,7,14))',kind:'rss',url:'https://futureoflife.org/feed/' },
  { id:'partnership-ai',name:'Partnership on AI',short:'PAI',color:'#6366f1',grad:'linear-gradient(135deg,rgb(29,20,36),rgb(11,8,14))',kind:'rss',url:'https://partnershiponai.org/feed/' },
  { id:'arxiv',name:'arXiv cs.AI',short:'AXV',color:'#b91c1c',grad:'linear-gradient(135deg,rgb(55,5,4),rgb(22,2,1))',kind:'rss',url:'https://export.arxiv.org/rss/cs.AI' },
  { id:'arxiv-cl',name:'arXiv cs.CL',short:'A-CL',color:'#b91c1c',grad:'linear-gradient(135deg,rgb(55,5,4),rgb(22,2,1))',kind:'rss',url:'https://export.arxiv.org/rss/cs.CL' },
  { id:'arxiv-lg',name:'arXiv cs.LG',short:'A-LG',color:'#b91c1c',grad:'linear-gradient(135deg,rgb(55,5,4),rgb(22,2,1))',kind:'rss',url:'https://export.arxiv.org/rss/cs.LG' },
  { id:'arxiv-cv',name:'arXiv cs.CV',short:'A-CV',color:'#b91c1c',grad:'linear-gradient(135deg,rgb(55,5,4),rgb(22,2,1))',kind:'rss',url:'https://export.arxiv.org/rss/cs.CV' },
  { id:'arxiv-ne',name:'arXiv cs.NE',short:'A-NE',color:'#b91c1c',grad:'linear-gradient(135deg,rgb(55,5,4),rgb(22,2,1))',kind:'rss',url:'https://export.arxiv.org/rss/cs.NE' },
  { id:'arxiv-ir',name:'arXiv cs.IR',short:'A-IR',color:'#b91c1c',grad:'linear-gradient(135deg,rgb(55,5,4),rgb(22,2,1))',kind:'rss',url:'https://export.arxiv.org/rss/cs.IR' },
  { id:'arxiv-ro',name:'arXiv cs.RO',short:'A-RO',color:'#b91c1c',grad:'linear-gradient(135deg,rgb(55,5,4),rgb(22,2,1))',kind:'rss',url:'https://export.arxiv.org/rss/cs.RO' },
  { id:'arxiv-sd',name:'arXiv cs.SD',short:'A-SD',color:'#b91c1c',grad:'linear-gradient(135deg,rgb(55,5,4),rgb(22,2,1))',kind:'rss',url:'https://export.arxiv.org/rss/cs.SD' },
  { id:'arxiv-mm',name:'arXiv cs.MM',short:'A-MM',color:'#b91c1c',grad:'linear-gradient(135deg,rgb(55,5,4),rgb(22,2,1))',kind:'rss',url:'https://export.arxiv.org/rss/cs.MM' },
  { id:'arxiv-hc',name:'arXiv cs.HC',short:'A-HC',color:'#b91c1c',grad:'linear-gradient(135deg,rgb(55,5,4),rgb(22,2,1))',kind:'rss',url:'https://export.arxiv.org/rss/cs.HC' },
  { id:'arxiv-cr',name:'arXiv cs.CR',short:'A-CR',color:'#b91c1c',grad:'linear-gradient(135deg,rgb(55,5,4),rgb(22,2,1))',kind:'rss',url:'https://export.arxiv.org/rss/cs.CR' },
  { id:'arxiv-dc',name:'arXiv cs.DC',short:'A-DC',color:'#b91c1c',grad:'linear-gradient(135deg,rgb(55,5,4),rgb(22,2,1))',kind:'rss',url:'https://export.arxiv.org/rss/cs.DC' },
  { id:'arxiv-pl',name:'arXiv cs.PL',short:'A-PL',color:'#b91c1c',grad:'linear-gradient(135deg,rgb(55,5,4),rgb(22,2,1))',kind:'rss',url:'https://export.arxiv.org/rss/cs.PL' },
  { id:'arxiv-os',name:'arXiv cs.OS',short:'A-OS',color:'#b91c1c',grad:'linear-gradient(135deg,rgb(55,5,4),rgb(22,2,1))',kind:'rss',url:'https://export.arxiv.org/rss/cs.OS' },
  { id:'arxiv-se',name:'arXiv cs.SE',short:'A-SE',color:'#b91c1c',grad:'linear-gradient(135deg,rgb(55,5,4),rgb(22,2,1))',kind:'rss',url:'https://export.arxiv.org/rss/cs.SE' },
  { id:'arxiv-stat',name:'arXiv stat.ML',short:'A-SM',color:'#b91c1c',grad:'linear-gradient(135deg,rgb(55,5,4),rgb(22,2,1))',kind:'rss',url:'https://export.arxiv.org/rss/stat.ML' },
  { id:'techcrunch',name:'TechCrunch AI',short:'TC',color:'#22c55e',grad:'linear-gradient(135deg,rgb(10,39,14),rgb(4,15,5))',kind:'rss',url:'https://techcrunch.com/category/artificial-intelligence/feed/' },
  { id:'venturebeat',name:'VentureBeat AI',short:'VB',color:'#f97316',grad:'linear-gradient(135deg,rgb(74,23,3),rgb(29,9,1))',kind:'rss',url:'https://venturebeat.com/category/ai/feed/' },
  { id:'venturebeat-all',name:'VentureBeat',short:'VB-G',color:'#f97316',grad:'linear-gradient(135deg,rgb(74,23,3),rgb(29,9,1))',kind:'rss',url:'https://venturebeat.com/feed/' },
  { id:'wired',name:'Wired AI',short:'WRD',color:'#ffffff',grad:'linear-gradient(135deg,rgb(76,51,38),rgb(30,20,15))',kind:'rss',url:'https://www.wired.com/feed/tag/ai/latest/rss' },
  { id:'wired-science',name:'Wired Science',short:'WRD-S',color:'#ffffff',grad:'linear-gradient(135deg,rgb(76,51,38),rgb(30,20,15))',kind:'rss',url:'https://www.wired.com/feed/category/science/latest/rss' },
  { id:'ars-technica',name:'Ars Technica AI',short:'ARS',color:'#fb923c',grad:'linear-gradient(135deg,rgb(75,29,9),rgb(30,11,3))',kind:'rss',url:'https://arstechnica.com/ai/feed/' },
  { id:'ars-science',name:'Ars Science',short:'ARS-S',color:'#fb923c',grad:'linear-gradient(135deg,rgb(75,29,9),rgb(30,11,3))',kind:'rss',url:'https://feeds.arstechnica.com/arstechnica/science' },
  { id:'ars-all',name:'Ars Technica',short:'ARS-A',color:'#fb923c',grad:'linear-gradient(135deg,rgb(75,29,9),rgb(30,11,3))',kind:'rss',url:'https://feeds.arstechnica.com/arstechnica/index' },
  { id:'verge',name:'The Verge AI',short:'VRG',color:'#c084fc',grad:'linear-gradient(135deg,rgb(57,26,37),rgb(23,10,15))',kind:'rss',url:'https://www.theverge.com/rss/ai-artificial-intelligence/index.xml' },
  { id:'verge-all',name:'The Verge',short:'VRG-G',color:'#c084fc',grad:'linear-gradient(135deg,rgb(57,26,37),rgb(23,10,15))',kind:'rss',url:'https://www.theverge.com/rss/index.xml' },
  { id:'bloomberg',name:'Bloomberg Tech',short:'BBG',color:'#2800d7',grad:'linear-gradient(135deg,rgb(12,0,32),rgb(4,0,12))',kind:'rss',url:'https://feeds.bloomberg.com/technology/news.rss' },
  { id:'ftai',name:'Financial Times AI',short:'FT',color:'#fff1e5',grad:'linear-gradient(135deg,rgb(76,48,34),rgb(30,19,13))',kind:'rss',url:'https://www.ft.com/artificial-intelligence?format=rss' },
  { id:'nyt-tech',name:'NYT Technology',short:'NYT',color:'#1a1a1a',grad:'linear-gradient(135deg,rgb(7,5,3),rgb(3,2,1))',kind:'rss',url:'https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml' },
  { id:'nyt-ai',name:'NYT AI',short:'NYT-A',color:'#1a1a1a',grad:'linear-gradient(135deg,rgb(7,5,3),rgb(3,2,1))',kind:'rss',url:'https://rss.nytimes.com/services/xml/rss/nyt/ArtificialIntelligence.xml' },
  { id:'bbc-tech',name:'BBC Technology',short:'BBC',color:'#bb1919',grad:'linear-gradient(135deg,rgb(56,5,3),rgb(22,2,1))',kind:'rss',url:'https://feeds.bbci.co.uk/news/technology/rss.xml' },
  { id:'guardian-ai',name:'Guardian AI',short:'GU-A',color:'#052962',grad:'linear-gradient(135deg,rgb(1,8,14),rgb(0,3,5))',kind:'rss',url:'https://www.theguardian.com/technology/artificialintelligence/rss' },
  { id:'guardian-tech',name:'Guardian Tech',short:'GU-T',color:'#052962',grad:'linear-gradient(135deg,rgb(1,8,14),rgb(0,3,5))',kind:'rss',url:'https://www.theguardian.com/technology/rss' },
  { id:'the-register',name:'The Register',short:'REG',color:'#ff6600',grad:'linear-gradient(135deg,rgb(76,20,0),rgb(30,8,0))',kind:'rss',url:'https://www.theregister.com/headlines.atom' },
  { id:'zdnet-ai',name:'ZDNet AI',short:'ZD',color:'#ef4444',grad:'linear-gradient(135deg,rgb(71,13,10),rgb(28,5,4))',kind:'rss',url:'https://www.zdnet.com/topic/artificial-intelligence/rss.xml' },
  { id:'cnet-ai',name:'CNET AI',short:'CN',color:'#0668E1',grad:'linear-gradient(135deg,rgb(1,20,33),rgb(0,8,13))',kind:'rss',url:'https://www.cnet.com/rss/ai/' },
  { id:'tnw',name:'The Next Web',short:'TNW',color:'#ff5a36',grad:'linear-gradient(135deg,rgb(76,18,8),rgb(30,7,3))',kind:'rss',url:'https://thenextweb.com/feed' },
  { id:'siliconangle',name:'SiliconANGLE',short:'SA',color:'#38bdf8',grad:'linear-gradient(135deg,rgb(16,37,37),rgb(6,15,14))',kind:'rss',url:'https://siliconangle.com/feed/' },
  { id:'techmeme',name:'Techmeme',short:'TM',color:'#e2e8f0',grad:'linear-gradient(135deg,rgb(67,46,36),rgb(27,18,14))',kind:'rss',url:'https://techmeme.com/feed.xml' },
  { id:'slashdot',name:'Slashdot AI',short:'SLD',color:'#006666',grad:'linear-gradient(135deg,rgb(0,20,15),rgb(0,8,6))',kind:'rss',url:'https://rss.slashdot.org/Slashdot/slashdotAI' },
  { id:'simonw',name:'Simon Willison',short:'SW',color:'#fbbf24',grad:'linear-gradient(135deg,rgb(75,38,5),rgb(30,15,2))',kind:'rss',url:'https://simonwillison.net/atom/everything/' },
  { id:'oneusefulthing',name:'One Useful Thing',short:'OUT',color:'#fb7185',grad:'linear-gradient(135deg,rgb(75,22,19),rgb(30,9,7))',kind:'rss',url:'https://www.oneusefulthing.org/feed' },
  { id:'importai',name:'Import AI',short:'IAI',color:'#a78bfa',grad:'linear-gradient(135deg,rgb(50,27,37),rgb(20,11,15))',kind:'rss',url:'https://importai.substack.com/feed' },
  { id:'thegradient',name:'The Gradient',short:'GRD',color:'#6ee7b7',grad:'linear-gradient(135deg,rgb(33,46,27),rgb(13,18,10))',kind:'rss',url:'https://thegradient.pub/rss/' },
  { id:'lillog',name:'Lil Log',short:'LL',color:'#f472b6',grad:'linear-gradient(135deg,rgb(73,22,27),rgb(29,9,10))',kind:'rss',url:'https://lilianweng.github.io/index.xml' },
  { id:'latent',name:'Latent Space',short:'LT',color:'#818cf8',grad:'linear-gradient(135deg,rgb(38,28,37),rgb(15,11,14))',kind:'rss',url:'https://www.latent.space/feed' },
  { id:'raschka',name:'Ahead of AI',short:'AAI',color:'#f472b6',grad:'linear-gradient(135deg,rgb(73,22,27),rgb(29,9,10))',kind:'rss',url:'https://magazine.sebastianraschka.com/feed' },
  { id:'chiphuyen',name:'Chip Huyen',short:'CH',color:'#5eead4',grad:'linear-gradient(135deg,rgb(28,46,31),rgb(11,18,12))',kind:'rss',url:'https://huyenchip.com/feed.xml' },
  { id:'sequence',name:'The Sequence',short:'SEQ',color:'#4ade80',grad:'linear-gradient(135deg,rgb(22,44,19),rgb(8,17,7))',kind:'rss',url:'https://thesequence.substack.com/feed' },
  { id:'interconnects',name:'Interconnects',short:'INT',color:'#a78bfa',grad:'linear-gradient(135deg,rgb(50,27,37),rgb(20,11,15))',kind:'rss',url:'https://www.interconnects.ai/feed' },
  { id:'towardsai',name:'Towards AI',short:'TAI',color:'#f59e0b',grad:'linear-gradient(135deg,rgb(73,31,1),rgb(29,12,0))',kind:'rss',url:'https://pub.towardsai.net/feed' },
  { id:'oreilly',name:'O Reilly AI',short:'ORL',color:'#c72228',grad:'linear-gradient(135deg,rgb(59,6,6),rgb(23,2,2))',kind:'rss',url:'https://www.oreilly.com/radar/feed/' },
  { id:'distill',name:'Distill.pub',short:'DIS',color:'#0ea5e9',grad:'linear-gradient(135deg,rgb(4,33,34),rgb(1,13,13))',kind:'rss',url:'https://distill.pub/rss.xml' },
  { id:'twiml',name:'TWIML AI',short:'TW',color:'#8b5cf6',grad:'linear-gradient(135deg,rgb(41,18,36),rgb(16,7,14))',kind:'rss',url:'https://twimlai.com/feed/' },
  { id:'decoder',name:'The Decoder',short:'DEC',color:'#60a5fa',grad:'linear-gradient(135deg,rgb(28,33,37),rgb(11,13,15))',kind:'rss',url:'https://the-decoder.com/feed/' },
  { id:'lastweekinai',name:'Last Week in AI',short:'LWAI',color:'#6366f1',grad:'linear-gradient(135deg,rgb(29,20,36),rgb(11,8,14))',kind:'rss',url:'https://lastweekin.ai/feed' },
  { id:'aiweekly',name:'AI Weekly',short:'AWK',color:'#14b8a6',grad:'linear-gradient(135deg,rgb(6,36,24),rgb(2,14,9))',kind:'rss',url:'https://aiweekly.co/feed' },
  { id:'airesearch',name:'AI Research Digest',short:'ARD',color:'#6366f1',grad:'linear-gradient(135deg,rgb(29,20,36),rgb(11,8,14))',kind:'rss',url:'https://buttondown.com/ainews/rss' },
  { id:'allenai',name:'Allen AI',short:'AI2',color:'#f59e0b',grad:'linear-gradient(135deg,rgb(73,31,1),rgb(29,12,0))',kind:'rss',url:'https://allenai.org/rss.xml' },
  { id:'bair',name:'BAIR',short:'BAI',color:'#f5c518',grad:'linear-gradient(135deg,rgb(73,39,3),rgb(29,15,1))',kind:'rss',url:'https://bair.berkeley.edu/blog/feed.xml' },
  { id:'mitnews',name:'MIT News AI',short:'MITN',color:'#ff5a36',grad:'linear-gradient(135deg,rgb(76,18,8),rgb(30,7,3))',kind:'rss',url:'https://news.mit.edu/rss/topic/artificial-intelligence2' },
  { id:'aihub',name:'AI Hub',short:'AIH',color:'#ff6600',grad:'linear-gradient(135deg,rgb(76,20,0),rgb(30,8,0))',kind:'rss',url:'https://aihub.org/feed/' },
  { id:'marktechpost',name:'MarkTechPost',short:'MTP',color:'#fb923c',grad:'linear-gradient(135deg,rgb(75,29,9),rgb(30,11,3))',kind:'rss',url:'https://www.marktechpost.com/feed/' },
  { id:'kdnuggets',name:'KDnuggets',short:'KDN',color:'#f8e71c',grad:'linear-gradient(135deg,rgb(74,46,4),rgb(29,18,1))',kind:'rss',url:'https://www.kdnuggets.com/feed' },
  { id:'mlmastery',name:'ML Mastery',short:'MLM',color:'#f97316',grad:'linear-gradient(135deg,rgb(74,23,3),rgb(29,9,1))',kind:'rss',url:'https://machinelearningmastery.com/feed/' },
  { id:'analyticsinsight',name:'Analytics Insight',short:'AI-INS',color:'#20beff',grad:'linear-gradient(135deg,rgb(9,38,38),rgb(3,15,15))',kind:'rss',url:'https://www.analyticsinsight.net/feed/' },
  { id:'ai-news',name:'AI News',short:'AI-N',color:'#3b82f6',grad:'linear-gradient(135deg,rgb(17,26,36),rgb(7,10,14))',kind:'rss',url:'https://www.artificialintelligence-news.com/feed/' },
  { id:'quanta',name:'Quanta Magazine',short:'QNT',color:'#f59e0b',grad:'linear-gradient(135deg,rgb(73,31,1),rgb(29,12,0))',kind:'rss',url:'https://www.quantamagazine.org/feed/' },
  { id:'towardsds',name:'Towards Data Science',short:'TDS',color:'#7c3aed',grad:'linear-gradient(135deg,rgb(37,11,35),rgb(14,4,14))',kind:'rss',url:'https://towardsdatascience.com/feed' },
  { id:'infoq',name:'InfoQ AI/ML',short:'IQ',color:'#2874a6',grad:'linear-gradient(135deg,rgb(12,23,24),rgb(4,9,9))',kind:'rss',url:'https://feed.infoq.com/ai-ml-data-eng' },
  { id:'opensource',name:'Open Source.com',short:'OSS',color:'#5c7cfa',grad:'linear-gradient(135deg,rgb(27,24,37),rgb(11,9,15))',kind:'rss',url:'https://opensource.com/feed' },
  { id:'devto-ai',name:'DEV AI',short:'DV-A',color:'#08090a',grad:'linear-gradient(135deg,rgb(2,1,1),rgb(0,0,0))',kind:'rss',url:'https://dev.to/feed/tag/ai' },
  { id:'devto-ml',name:'DEV ML',short:'DV-ML',color:'#08090a',grad:'linear-gradient(135deg,rgb(2,1,1),rgb(0,0,0))',kind:'rss',url:'https://dev.to/feed/tag/machinelearning' },
  { id:'devto-llm',name:'DEV LLM',short:'DV-LM',color:'#08090a',grad:'linear-gradient(135deg,rgb(2,1,1),rgb(0,0,0))',kind:'rss',url:'https://dev.to/feed/tag/llm' },
  { id:'devto-nlp',name:'DEV NLP',short:'DV-NL',color:'#08090a',grad:'linear-gradient(135deg,rgb(2,1,1),rgb(0,0,0))',kind:'rss',url:'https://dev.to/feed/tag/nlp' },
  { id:'devto-dl',name:'DEV Deep Learning',short:'DV-DL',color:'#08090a',grad:'linear-gradient(135deg,rgb(2,1,1),rgb(0,0,0))',kind:'rss',url:'https://dev.to/feed/tag/deeplearning' },
  { id:'devto-pytorch',name:'DEV PyTorch',short:'DV-PT',color:'#08090a',grad:'linear-gradient(135deg,rgb(2,1,1),rgb(0,0,0))',kind:'rss',url:'https://dev.to/feed/tag/pytorch' },
  { id:'devto-tf',name:'DEV TensorFlow',short:'DV-TF',color:'#08090a',grad:'linear-gradient(135deg,rgb(2,1,1),rgb(0,0,0))',kind:'rss',url:'https://dev.to/feed/tag/tensorflow' },
  { id:'devto-transformers',name:'DEV Transformers',short:'DV-TR',color:'#08090a',grad:'linear-gradient(135deg,rgb(2,1,1),rgb(0,0,0))',kind:'rss',url:'https://dev.to/feed/tag/transformers' },
  { id:'devto-python',name:'DEV Python',short:'DV-PY',color:'#08090a',grad:'linear-gradient(135deg,rgb(2,1,1),rgb(0,0,0))',kind:'rss',url:'https://dev.to/feed/tag/python' },
  { id:'devto-javascript',name:'DEV JavaScript',short:'DV-JS',color:'#08090a',grad:'linear-gradient(135deg,rgb(2,1,1),rgb(0,0,0))',kind:'rss',url:'https://dev.to/feed/tag/javascript' },
  { id:'devto-webdev',name:'DEV WebDev',short:'DV-WD',color:'#08090a',grad:'linear-gradient(135deg,rgb(2,1,1),rgb(0,0,0))',kind:'rss',url:'https://dev.to/feed/tag/webdev' },
  { id:'devto-programming',name:'DEV Programming',short:'DV-PR',color:'#08090a',grad:'linear-gradient(135deg,rgb(2,1,1),rgb(0,0,0))',kind:'rss',url:'https://dev.to/feed/tag/programming' },
  { id:'medium-ai',name:'Medium AI',short:'MD-A',color:'#000000',grad:'linear-gradient(135deg,rgb(0,0,0),rgb(0,0,0))',kind:'rss',url:'https://medium.com/feed/tag/artificial-intelligence' },
  { id:'medium-ml',name:'Medium ML',short:'MD-ML',color:'#000000',grad:'linear-gradient(135deg,rgb(0,0,0),rgb(0,0,0))',kind:'rss',url:'https://medium.com/feed/tag/machine-learning' },
  { id:'medium-dl',name:'Medium DL',short:'MD-DL',color:'#000000',grad:'linear-gradient(135deg,rgb(0,0,0),rgb(0,0,0))',kind:'rss',url:'https://medium.com/feed/tag/deep-learning' },
  { id:'medium-nlp',name:'Medium NLP',short:'MD-NL',color:'#000000',grad:'linear-gradient(135deg,rgb(0,0,0),rgb(0,0,0))',kind:'rss',url:'https://medium.com/feed/tag/natural-language-processing' },
  { id:'medium-pytorch',name:'Medium PyTorch',short:'MD-PT',color:'#000000',grad:'linear-gradient(135deg,rgb(0,0,0),rgb(0,0,0))',kind:'rss',url:'https://medium.com/feed/tag/pytorch' },
  { id:'medium-tf',name:'Medium TensorFlow',short:'MD-TF',color:'#000000',grad:'linear-gradient(135deg,rgb(0,0,0),rgb(0,0,0))',kind:'rss',url:'https://medium.com/feed/tag/tensorflow' },
  { id:'medium-ds',name:'Medium Data Science',short:'MD-DS',color:'#000000',grad:'linear-gradient(135deg,rgb(0,0,0),rgb(0,0,0))',kind:'rss',url:'https://medium.com/feed/tag/data-science' },
  { id:'medium-gpt',name:'Medium GPT',short:'MD-GP',color:'#000000',grad:'linear-gradient(135deg,rgb(0,0,0),rgb(0,0,0))',kind:'rss',url:'https://medium.com/feed/tag/chatgpt' },
  { id:'medium-llm',name:'Medium LLM',short:'MD-LM',color:'#000000',grad:'linear-gradient(135deg,rgb(0,0,0),rgb(0,0,0))',kind:'rss',url:'https://medium.com/feed/tag/large-language-models' },
  { id:'medium-python',name:'Medium Python',short:'MD-PY',color:'#000000',grad:'linear-gradient(135deg,rgb(0,0,0),rgb(0,0,0))',kind:'rss',url:'https://medium.com/feed/tag/python' },
  { id:'medium-javascript',name:'Medium JavaScript',short:'MD-JS',color:'#000000',grad:'linear-gradient(135deg,rgb(0,0,0),rgb(0,0,0))',kind:'rss',url:'https://medium.com/feed/tag/javascript' },
  { id:'medium-react',name:'Medium React',short:'MD-RE',color:'#000000',grad:'linear-gradient(135deg,rgb(0,0,0),rgb(0,0,0))',kind:'rss',url:'https://medium.com/feed/tag/reactjs' },
  { id:'kaggle',name:'Kaggle Blog',short:'KGL',color:'#20beff',grad:'linear-gradient(135deg,rgb(9,38,38),rgb(3,15,15))',kind:'rss',url:'https://medium.com/feed/kaggle-blog' },
  { id:'reddit-ml',name:'r/MachineLearning',short:'RML',color:'#ff4500',grad:'linear-gradient(135deg,rgb(76,13,0),rgb(30,5,0))',kind:'rss',url:'https://www.reddit.com/r/MachineLearning/top/.rss?t=day' },
  { id:'reddit-ai',name:'r/artificial',short:'RAI',color:'#ff6314',grad:'linear-gradient(135deg,rgb(76,19,3),rgb(30,7,1))',kind:'rss',url:'https://www.reddit.com/r/artificial/top/.rss?t=day' },
  { id:'reddit-llama',name:'r/LocalLLaMA',short:'RLL',color:'#7c3aed',grad:'linear-gradient(135deg,rgb(37,11,35),rgb(14,4,14))',kind:'rss',url:'https://www.reddit.com/r/LocalLLaMA/top/.rss?t=day' },
  { id:'reddit-chatgpt',name:'r/ChatGPT',short:'RCG',color:'#10a37f',grad:'linear-gradient(135deg,rgb(4,32,19),rgb(1,13,7))',kind:'rss',url:'https://www.reddit.com/r/ChatGPT/top/.rss?t=day' },
  { id:'reddit-openai',name:'r/OpenAI',short:'ROA',color:'#10a37f',grad:'linear-gradient(135deg,rgb(4,32,19),rgb(1,13,7))',kind:'rss',url:'https://www.reddit.com/r/OpenAI/top/.rss?t=day' },
  { id:'reddit-dl',name:'r/deeplearning',short:'RDL',color:'#6366f1',grad:'linear-gradient(135deg,rgb(29,20,36),rgb(11,8,14))',kind:'rss',url:'https://www.reddit.com/r/deeplearning/top/.rss?t=day' },
  { id:'reddit-cv',name:'r/computervision',short:'RCV',color:'#06b6d4',grad:'linear-gradient(135deg,rgb(1,36,31),rgb(0,14,12))',kind:'rss',url:'https://www.reddit.com/r/computervision/top/.rss?t=day' },
  { id:'reddit-sd',name:'r/StableDiffusion',short:'RSD',color:'#a855f7',grad:'linear-gradient(135deg,rgb(50,17,37),rgb(20,6,14))',kind:'rss',url:'https://www.reddit.com/r/StableDiffusion/top/.rss?t=day' },
  { id:'reddit-mj',name:'r/midjourney',short:'RMJ',color:'#ec4899',grad:'linear-gradient(135deg,rgb(70,14,22),rgb(28,5,9))',kind:'rss',url:'https://www.reddit.com/r/midjourney/top/.rss?t=day' },
  { id:'reddit-robotics',name:'r/robotics',short:'RRO',color:'#22c55e',grad:'linear-gradient(135deg,rgb(10,39,14),rgb(4,15,5))',kind:'rss',url:'https://www.reddit.com/r/robotics/top/.rss?t=day' },
  { id:'reddit-singularity',name:'r/singularity',short:'RSG',color:'#f59e0b',grad:'linear-gradient(135deg,rgb(73,31,1),rgb(29,12,0))',kind:'rss',url:'https://www.reddit.com/r/singularity/top/.rss?t=day' },
  { id:'reddit-futurology',name:'r/Futurology',short:'RFU',color:'#8b5cf6',grad:'linear-gradient(135deg,rgb(41,18,36),rgb(16,7,14))',kind:'rss',url:'https://www.reddit.com/r/Futurology/top/.rss?t=day' },
  { id:'reddit-ds',name:'r/datascience',short:'RDS',color:'#3b82f6',grad:'linear-gradient(135deg,rgb(17,26,36),rgb(7,10,14))',kind:'rss',url:'https://www.reddit.com/r/datascience/top/.rss?t=day' },
  { id:'reddit-python',name:'r/Python',short:'RPY',color:'#3776ab',grad:'linear-gradient(135deg,rgb(16,23,25),rgb(6,9,10))',kind:'rss',url:'https://www.reddit.com/r/Python/top/.rss?t=day' },
  { id:'reddit-javascript',name:'r/JavaScript',short:'RJS',color:'#f7df1e',grad:'linear-gradient(135deg,rgb(74,44,4),rgb(29,17,1))',kind:'rss',url:'https://www.reddit.com/r/javascript/top/.rss?t=day' },
  { id:'reddit-rust',name:'r/Rust',short:'RRS',color:'#dea584',grad:'linear-gradient(135deg,rgb(66,33,19),rgb(26,13,7))',kind:'rss',url:'https://www.reddit.com/r/rust/top/.rss?t=day' },
  { id:'reddit-selfhosted',name:'r/selfhosted',short:'RSH',color:'#f97316',grad:'linear-gradient(135deg,rgb(74,23,3),rgb(29,9,1))',kind:'rss',url:'https://www.reddit.com/r/selfhosted/top/.rss?t=day' },
  { id:'reddit-homeauto',name:'r/homeautomation',short:'RHA',color:'#22c55e',grad:'linear-gradient(135deg,rgb(10,39,14),rgb(4,15,5))',kind:'rss',url:'https://www.reddit.com/r/homeautomation/top/.rss?t=day' },
  { id:'yannic',name:'Yannic Kilcher',short:'YK',color:'#ef4444',grad:'linear-gradient(135deg,rgb(71,13,10),rgb(28,5,4))',kind:'rss',url:'https://www.youtube.com/feeds/videos.xml?channel_id=UCZHmQk67mSJgfCCTn7xBfew' },
  { id:'2minpapers',name:'Two Minute Papers',short:'2MP',color:'#ff0000',grad:'linear-gradient(135deg,rgb(76,0,0),rgb(30,0,0))',kind:'rss',url:'https://www.youtube.com/feeds/videos.xml?channel_id=UCbfYPyITQ-7l4upoX8nvctg' },
  { id:'aiexplained',name:'AI Explained',short:'AIE',color:'#ff4444',grad:'linear-gradient(135deg,rgb(76,13,10),rgb(30,5,4))',kind:'rss',url:'https://www.youtube.com/feeds/videos.xml?channel_id=UCNJ1Ymd5yFuUPtn21xtRbbw' },
  { id:'3b1b',name:'3Blue1Brown',short:'3BB',color:'#0066cc',grad:'linear-gradient(135deg,rgb(0,20,30),rgb(0,8,12))',kind:'rss',url:'https://www.youtube.com/feeds/videos.xml?channel_id=UCYO_jab_esuFRV4b17AJtAw' },
  { id:'fireship',name:'Fireship',short:'FSH',color:'#ff6600',grad:'linear-gradient(135deg,rgb(76,20,0),rgb(30,8,0))',kind:'rss',url:'https://www.youtube.com/feeds/videos.xml?channel_id=UCsBjURrPoezykLs9EqgamOA' },
  { id:'statquest',name:'StatQuest',short:'STQ',color:'#ff0000',grad:'linear-gradient(135deg,rgb(76,0,0),rgb(30,0,0))',kind:'rss',url:'https://www.youtube.com/feeds/videos.xml?channel_id=UCtYLUTT7i22jOq6ZdL19LcA' },
  { id:'lobsters',name:'Lobsters AI',short:'LOB',color:'#ac130d',grad:'linear-gradient(135deg,rgb(51,3,1),rgb(20,1,0))',kind:'lobsters',url:null },
  { id:'lobsters-ml',name:'Lobsters ML',short:'LOML',color:'#dc2626',grad:'linear-gradient(135deg,rgb(66,7,5),rgb(26,3,2))',kind:'rss',url:'https://lobste.rs/t/ml.rss' },
  { id:'lobsters-prog',name:'Lobsters Programming',short:'LOPR',color:'#b91c1c',grad:'linear-gradient(135deg,rgb(55,5,4),rgb(22,2,1))',kind:'rss',url:'https://lobste.rs/t/programming.rss' },
  { id:'lobsters-python',name:'Lobsters Python',short:'LOPY',color:'#3776ab',grad:'linear-gradient(135deg,rgb(16,23,25),rgb(6,9,10))',kind:'rss',url:'https://lobste.rs/t/python.rss' },
  { id:'lobsters-rust',name:'Lobsters Rust',short:'LORS',color:'#dea584',grad:'linear-gradient(135deg,rgb(66,33,19),rgb(26,13,7))',kind:'rss',url:'https://lobste.rs/t/rust.rss' },
  { id:'lobsters-js',name:'Lobsters JavaScript',short:'LOJS',color:'#f7df1e',grad:'linear-gradient(135deg,rgb(74,44,4),rgb(29,17,1))',kind:'rss',url:'https://lobste.rs/t/javascript.rss' },
  { id:'lobsters-go',name:'Lobsters Go',short:'LOGO',color:'#00ADD8',grad:'linear-gradient(135deg,rgb(0,34,32),rgb(0,13,12))',kind:'rss',url:'https://lobste.rs/t/go.rss' },
  { id:'robot-report',name:'The Robot Report',short:'RR',color:'#10b981',grad:'linear-gradient(135deg,rgb(4,37,19),rgb(1,14,7))',kind:'rss',url:'https://www.therobotreport.com/feed/' },
  { id:'ieee-robotics',name:'IEEE Robotics',short:'SP-R',color:'#0066cc',grad:'linear-gradient(135deg,rgb(0,20,30),rgb(0,8,12))',kind:'rss',url:'https://spectrum.ieee.org/feeds/topic/robotics.rss' },
  { id:'science',name:'Science',short:'SCI',color:'#000000',grad:'linear-gradient(135deg,rgb(0,0,0),rgb(0,0,0))',kind:'rss',url:'https://www.science.org/rss/current.xml' },
  { id:'sciencedaily',name:'ScienceDaily AI',short:'SDA',color:'#0099cc',grad:'linear-gradient(135deg,rgb(0,0,0),rgb(0,0,0))',kind:'rss',url:'https://www.sciencedaily.com/rss/computers_math/artificial_intelligence.xml' },
  { id:'spacenews',name:'SpaceNews',short:'SPN',color:'#003366',grad:'linear-gradient(135deg,rgb(0,0,0),rgb(0,0,0))',kind:'rss',url:'https://spacenews.com/feed/' },
  { id:'nasa',name:'NASA',short:'NASA',color:'#0B3D91',grad:'linear-gradient(135deg,rgb(0,0,0),rgb(0,0,0))',kind:'rss',url:'https://www.nasa.gov/rss/dyn/breaking_news.rss' },
  { id:'coindesk',name:'CoinDesk',short:'CDK',color:'#144DC1',grad:'linear-gradient(135deg,rgb(0,0,0),rgb(0,0,0))',kind:'rss',url:'https://www.coindesk.com/arc/outboundfeeds/rss/' },
  { id:'decrypt',name:'Decrypt',short:'DCR',color:'#000000',grad:'linear-gradient(135deg,rgb(0,0,0),rgb(0,0,0))',kind:'rss',url:'https://decrypt.co/feed' },
  { id:'gamedev',name:'Game Developer',short:'GDE',color:'#000000',grad:'linear-gradient(135deg,rgb(0,0,0),rgb(0,0,0))',kind:'rss',url:'https://www.gamedeveloper.com/rss.xml' },
  { id:'producthunt',name:'Product Hunt',short:'PH',color:'#da552f',grad:'linear-gradient(135deg,rgb(55,11,7),rgb(22,4,3))',kind:'rss',url:'https://www.producthunt.com/feed' },
  { id:'stackoverflow',name:'Stack Overflow',short:'SO',color:'#f48024',grad:'linear-gradient(135deg,rgb(62,20,2),rgb(24,8,1))',kind:'rss',url:'https://stackoverflow.blog/feed/' },
  { id:'github-blog',name:'GitHub Blog',short:'GH',color:'#24292e',grad:'linear-gradient(135deg,rgb(11,8,6),rgb(4,3,2))',kind:'rss',url:'https://github.blog/tag/ai/feed/' },
  { id:'github-aiml',name:'GitHub AI/ML',short:'GH-A',color:'#24292e',grad:'linear-gradient(135deg,rgb(11,8,6),rgb(4,3,2))',kind:'rss',url:'https://github.blog/ai-and-ml/feed/' },
  { id:'github-actions',name:'GitHub Actions',short:'GH-C',color:'#2088ff',grad:'linear-gradient(135deg,rgb(9,16,25),rgb(4,6,10))',kind:'rss',url:'https://github.blog/changelog/label/actions/feed/' },
  { id:'ansible',name:'Ansible',short:'ANS',color:'#EE0000',grad:'linear-gradient(135deg,rgb(68,0,0),rgb(27,0,0))',kind:'rss',url:'https://www.ansible.com/blog/rss.xml' },
  { id:'clickhouse',name:'ClickHouse',short:'CH',color:'#FFCC01',grad:'linear-gradient(135deg,rgb(76,32,0),rgb(30,13,0))',kind:'rss',url:'https://clickhouse.com/blog/rss' },
  { id:'pymnts',name:'PYMNTS',short:'PYN',color:'#0066cc',grad:'linear-gradient(135deg,rgb(0,13,20),rgb(0,5,8))',kind:'rss',url:'https://www.pymnts.com/feed/' },
  { id:'tradingmarkets',name:'Trading Markets',short:'TMK',color:'#006600',grad:'linear-gradient(135deg,rgb(0,20,0),rgb(0,8,0))',kind:'rss',url:'https://www.tradingmarkets.com/rss' },
  { id:'artificiallawyer',name:'Artificial Lawyer',short:'AL',color:'#000080',grad:'linear-gradient(135deg,rgb(0,0,32),rgb(0,0,12))',kind:'rss',url:'https://www.artificiallawyer.com/feed/' },
  { id:'uk-gov-ai',name:'UK Gov AI',short:'UK',color:'#012169',grad:'linear-gradient(135deg,rgb(0,1,15),rgb(0,0,6))',kind:'rss',url:'https://www.gov.uk/search/all?topics%5B%5D=artificial-intelligence&format=atom' },
  { id:'israel-innovation',name:'Israel Innovation',short:'IL',color:'#0038b8',grad:'linear-gradient(135deg,rgb(0,5,28),rgb(0,2,11))',kind:'rss',url:'https://innovationisrael.org.il/feed/' },

  // ── Additional AI Research Labs ──
  { id:'anthropic',name:'Anthropic',short:'ANT',color:'#d97706',grad:'linear-gradient(135deg,rgb(54,23,0),rgb(21,9,0))',kind:'rss',url:'https://news.google.com/rss/search?q=site:anthropic.com&hl=en-US&gl=US&ceid=US:en' },
  { id:'ai2',name:'Allen Institute for AI',short:'AI2',color:'#0066cc',grad:'linear-gradient(135deg,rgb(0,13,20),rgb(0,5,8))',kind:'rss',url:'https://news.google.com/rss/search?q=site:allenai.org&hl=en-US&gl=US&ceid=US:en' },
  { id:'eleutherai',name:'EleutherAI',short:'ELU',color:'#8b5cf6',grad:'linear-gradient(135deg,rgb(41,18,36),rgb(16,7,14))',kind:'rss',url:'https://news.google.com/rss/search?q=site:eleuther.ai&hl=en-US&gl=US&ceid=US:en' },
  { id:'fair',name:'FAIR (Meta AI)',short:'FAIR',color:'#0066ff',grad:'linear-gradient(135deg,rgb(0,17,38),rgb(0,7,15))',kind:'rss',url:'https://about.fb.com/news/feed/' },
  { id:'google-brain',name:'Google Brain',short:'GBR',color:'#4285F4',grad:'linear-gradient(135deg,rgb(19,26,36),rgb(7,10,14))',kind:'rss',url:'https://research.google/blog/rss/' },

  // ── AI News Aggregators ──
  { id:'the-batch',name:'The Batch (Andrew Ng)',short:'BATCH',color:'#10b981',grad:'linear-gradient(135deg,rgb(4,39,15),rgb(1,15,6))',kind:'rss',url:'https://www.deeplearning.ai/the-batch/feed/' },
  { id:'import-ai',name:'Import AI',short:'IMP',color:'#f59e0b',grad:'linear-gradient(135deg,rgb(54,31,0),rgb(21,12,0))',kind:'rss',url:'https://importai.substack.com/feed' },
  { id:'ai-weekly',name:'AI Weekly',short:'AIW',color:'#6366f1',grad:'linear-gradient(135deg,rgb(29,20,36),rgb(11,8,14))',kind:'rss',url:'https://aiweekly.co/rss/' },
  { id:'synced',name:'Synced',short:'SYN',color:'#0ea5e9',grad:'linear-gradient(135deg,rgb(0,33,43),rgb(0,13,17))',kind:'rss',url:'https://syncedreview.com/feed/' },
  { id:'venturebeat-ai',name:'VentureBeat AI',short:'VB-AI',color:'#ff6b35',grad:'linear-gradient(135deg,rgb(76,21,8),rgb(30,8,3))',kind:'rss',url:'https://venturebeat.com/category/ai/feed/' },
  { id:'the-information-ai',name:'The Information AI',short:'INFO',color:'#000000',grad:'linear-gradient(135deg,rgb(0,0,0),rgb(0,0,0))',kind:'rss',url:'https://www.theinformation.com/feed/ai' },

  // ── ML Platforms & Tools ──
  { id:'paperswithcode',name:'Papers with Code',short:'PWC',color:'#00a67e',grad:'linear-gradient(135deg,rgb(0,32,19),rgb(0,13,7))',kind:'rss',url:'https://paperswithcode.com/rss.xml' },
  { id:'mlcommons',name:'MLCommons',short:'MLC',color:'#6b21a8',grad:'linear-gradient(135deg,rgb(32,10,42),rgb(13,4,16))',kind:'rss',url:'https://mlcommons.org/feed/' },
  { id:'databricks',name:'Databricks',short:'DBR',color:'#ff3621',grad:'linear-gradient(135deg,rgb(68,8,5),rgb(27,3,2))',kind:'rss',url:'https://www.databricks.com/blog/feed.xml' },
  { id:'snowflake',name:'Snowflake',short:'SNW',color:'#29b5e8',grad:'linear-gradient(135deg,rgb(8,35,43),rgb(3,14,17))',kind:'rss',url:'https://www.snowflake.com/blog/feed/' },
  { id:'scale-ai',name:'Scale AI',short:'SCL',color:'#000000',grad:'linear-gradient(135deg,rgb(0,0,0),rgb(0,0,0))',kind:'rss',url:'https://scale.com/blog/rss.xml' },
  { id:'wandb-blog',name:'Weights & Biases Blog',short:'WBB',color:'#ffcc33',grad:'linear-gradient(135deg,rgb(76,40,7),rgb(30,16,3))',kind:'rss',url:'https://news.google.com/rss/search?q=site:wandb.ai&hl=en-US&gl=US&ceid=US:en' },

  // ── Academic Research Labs ──
  { id:'mit-csail',name:'MIT CSAIL',short:'CSAIL',color:'#a31f34',grad:'linear-gradient(135deg,rgb(40,3,5),rgb(16,1,2))',kind:'rss',url:'https://www.csail.mit.edu/rss.xml' },
  { id:'stanford-hai',name:'Stanford HAI',short:'HAI',color:'#8c1515',grad:'linear-gradient(135deg,rgb(35,3,3),rgb(14,1,1))',kind:'rss',url:'https://hai.stanford.edu/news/rss' },
  { id:'berkeley-bair',name:'Berkeley BAIR',short:'BAIR',color:'#003262',grad:'linear-gradient(135deg,rgb(0,8,19),rgb(0,3,7))',kind:'rss',url:'https://news.google.com/rss/search?q=site:bair.berkeley.edu&hl=en-US&gl=US&ceid=US:en' },
  { id:'cmu-ml',name:'CMU ML',short:'CMU',color:'#c41230',grad:'linear-gradient(135deg,rgb(48,3,5),rgb(19,1,2))',kind:'rss',url:'https://news.google.com/rss/search?q=site:ml.cmu.edu&hl=en-US&gl=US&ceid=US:en' },
  { id:'oxford-ml',name:'Oxford ML',short:'OXF',color:'#002147',grad:'linear-gradient(135deg,rgb(0,5,13),rgb(0,2,5))',kind:'rss',url:'https://www.ox.ac.uk/news/rss' },

  // ── AI Safety & Alignment ──
  { id:'center-ai-safety',name:'Center for AI Safety',short:'CAIS',color:'#dc2626',grad:'linear-gradient(135deg,rgb(66,7,5),rgb(26,3,2))',kind:'rss',url:'https://www.safe.ai/blog/rss.xml' },
  { id:'miri',name:'MIRI',short:'MIRI',color:'#7c3aed',grad:'linear-gradient(135deg,rgb(37,11,35),rgb(14,4,14))',kind:'rss',url:'https://intelligence.org/feed/' },
  { id:'anthropic-safety',name:'Anthropic Safety',short:'ANT-S',color:'#d97706',grad:'linear-gradient(135deg,rgb(54,23,0),rgb(21,9,0))',kind:'rss',url:'https://news.google.com/rss/search?q=site:anthropic.com%2Fresearch&hl=en-US&gl=US&ceid=US:en' },

  // ── Emerging AI Companies ──
  { id:'character-ai',name:'Character AI',short:'CHAI',color:'#c084fc',grad:'linear-gradient(135deg,rgb(48,13,48),rgb(19,5,19))',kind:'rss',url:'https://blog.character.ai/rss/' },
  { id:'perplexity',name:'Perplexity',short:'PPX',color:'#000000',grad:'linear-gradient(135deg,rgb(0,0,0),rgb(0,0,0))',kind:'rss',url:'https://www.perplexity.ai/blog/rss.xml' },
  { id:'you-com',name:'You.com',short:'YOU',color:'#6366f1',grad:'linear-gradient(135deg,rgb(29,20,36),rgb(11,8,14))',kind:'rss',url:'https://you.com/blog/rss.xml' },
  { id:'inflection',name:'Inflection AI',short:'INF',color:'#14b8a6',grad:'linear-gradient(135deg,rgb(5,37,33),rgb(2,15,13))',kind:'rss',url:'https://news.google.com/rss/search?q=site:inflection.ai&hl=en-US&gl=US&ceid=US:en' },
  { id:'adept',name:'Adept AI',short:'ADP',color:'#8b5cf6',grad:'linear-gradient(135deg,rgb(41,18,36),rgb(16,7,14))',kind:'rss',url:'https://www.adept.ai/blog/rss.xml' },
  { id:'together-ai',name:'Together AI',short:'TGR',color:'#f97316',grad:'linear-gradient(135deg,rgb(74,23,3),rgb(29,9,1))',kind:'rss',url:'https://www.together.ai/blog/rss.xml' },
  { id:'cohere-blog',name:'Cohere Blog',short:'COH',color:'#39594D',grad:'linear-gradient(135deg,rgb(17,17,11),rgb(6,7,4))',kind:'rss',url:'https://cohere.com/blog/rss' },
  { id:'stability-ai',name:'Stability AI',short:'STB',color:'#ffffff',grad:'linear-gradient(135deg,rgb(76,51,38),rgb(30,20,15))',kind:'rss',url:'https://stability.ai/blog/rss.xml' },
  { id:'runway',name:'Runway',short:'RWY',color:'#000000',grad:'linear-gradient(135deg,rgb(0,0,0),rgb(0,0,0))',kind:'rss',url:'https://runwayml.com/blog/rss.xml' },

  { id:'hn',name:'Hacker News',short:'HN',color:'#ff6600',grad:'linear-gradient(135deg,rgb(76,20,0),rgb(30,8,0))',kind:'hn',url:null },
  { id:'hn-best',name:'HN Best AI',short:'HN-B',color:'#ff6600',grad:'linear-gradient(135deg,rgb(76,20,0),rgb(30,8,0))',kind:'rss',url:'https://hnrss.org/best?q=AI+OR+LLM+OR+machine+learning' },
  { id:'devto',name:'DEV Community',short:'DEV',color:'#08090a',grad:'linear-gradient(135deg,rgb(2,1,1),rgb(0,0,0))',kind:'devto',url:null },

  // ── arXiv subcategories ────────────────────────────────────────
  { id:'arxiv-stat-ml',name:'arXiv stat.ML',short:'A-SML',color:'#b31b1b',grad:'linear-gradient(135deg,rgb(44,3,3),rgb(17,1,1))',kind:'rss',url:'https://rss.arxiv.org/rss/stat.ML' },
  { id:'arxiv-cs-ai',name:'arXiv cs.AI',short:'A-AI',color:'#b31b1b',grad:'linear-gradient(135deg,rgb(44,3,3),rgb(17,1,1))',kind:'rss',url:'https://rss.arxiv.org/rss/cs.AI' },
  { id:'arxiv-cs-cc',name:'arXiv cs.CC',short:'A-CC',color:'#b31b1b',grad:'linear-gradient(135deg,rgb(44,3,3),rgb(17,1,1))',kind:'rss',url:'https://rss.arxiv.org/rss/cs.CC' },
  { id:'arxiv-cs-cr',name:'arXiv cs.CR',short:'A-CR',color:'#b31b1b',grad:'linear-gradient(135deg,rgb(44,3,3),rgb(17,1,1))',kind:'rss',url:'https://rss.arxiv.org/rss/cs.CR' },
  { id:'arxiv-cs-dc',name:'arXiv cs.DC',short:'A-DC',color:'#b31b1b',grad:'linear-gradient(135deg,rgb(44,3,3),rgb(17,1,1))',kind:'rss',url:'https://rss.arxiv.org/rss/cs.DC' },
  { id:'arxiv-cs-hc',name:'arXiv cs.HC',short:'A-HC',color:'#b31b1b',grad:'linear-gradient(135deg,rgb(44,3,3),rgb(17,1,1))',kind:'rss',url:'https://rss.arxiv.org/rss/cs.HC' },
  { id:'arxiv-cs-ir',name:'arXiv cs.IR',short:'A-IR',color:'#b31b1b',grad:'linear-gradient(135deg,rgb(44,3,3),rgb(17,1,1))',kind:'rss',url:'https://rss.arxiv.org/rss/cs.IR' },
  { id:'arxiv-cs-mm',name:'arXiv cs.MM',short:'A-MM',color:'#b31b1b',grad:'linear-gradient(135deg,rgb(44,3,3),rgb(17,1,1))',kind:'rss',url:'https://rss.arxiv.org/rss/cs.MM' },
  { id:'arxiv-cs-ne',name:'arXiv cs.NE',short:'A-NE',color:'#b31b1b',grad:'linear-gradient(135deg,rgb(44,3,3),rgb(17,1,1))',kind:'rss',url:'https://rss.arxiv.org/rss/cs.NE' },
  { id:'arxiv-cs-pl',name:'arXiv cs.PL',short:'A-PL',color:'#b31b1b',grad:'linear-gradient(135deg,rgb(44,3,3),rgb(17,1,1))',kind:'rss',url:'https://rss.arxiv.org/rss/cs.PL' },
  { id:'arxiv-cs-ro',name:'arXiv cs.RO',short:'A-RO',color:'#b31b1b',grad:'linear-gradient(135deg,rgb(44,3,3),rgb(17,1,1))',kind:'rss',url:'https://rss.arxiv.org/rss/cs.RO' },
  { id:'arxiv-cs-sd',name:'arXiv cs.SD',short:'A-SD',color:'#b31b1b',grad:'linear-gradient(135deg,rgb(44,3,3),rgb(17,1,1))',kind:'rss',url:'https://rss.arxiv.org/rss/cs.SD' },
  { id:'arxiv-cs-se',name:'arXiv cs.SE',short:'A-SE',color:'#b31b1b',grad:'linear-gradient(135deg,rgb(44,3,3),rgb(17,1,1))',kind:'rss',url:'https://rss.arxiv.org/rss/cs.SE' },

  // ── More media ──────────────────────────────────────────────────
  { id:'ft-tech',name:'Financial Times Tech',short:'FT',color:'#f5f5f5',grad:'linear-gradient(135deg,rgb(40,40,40),rgb(15,15,15))',kind:'rss',url:'https://www.ft.com/rss/tech' },
  { id:'theverge-ai',name:'The Verge AI',short:'VRG',color:'#7c3aed',grad:'linear-gradient(135deg,rgb(37,11,35),rgb(14,4,14))',kind:'rss',url:'https://www.theverge.com/rss/ai-artificial-intelligence/index.xml' },
  { id:'wired-ai',name:'Wired AI',short:'WIR',color:'#000000',grad:'linear-gradient(135deg,rgb(0,0,0),rgb(0,0,0))',kind:'rss',url:'https://www.wired.com/feed/tag/ai/latest/rss' },
  { id:'ars-ai',name:'Ars Technica AI',short:'ARS',color:'#ff4500',grad:'linear-gradient(135deg,rgb(76,11,0),rgb(30,4,0))',kind:'rss',url:'https://arstechnica.com/tag/ai/feed/' },
  { id:'register-ai',name:'The Register',short:'REG',color:'#ff4500',grad:'linear-gradient(135deg,rgb(76,11,0),rgb(30,4,0))',kind:'rss',url:'https://www.theregister.com/headlines.atom' },

  // ── Dev.to tags ─────────────────────────────────────────────────
  { id:'devto-tensorflow',name:'DEV TensorFlow',short:'DEV-TF',color:'#ff6f00',grad:'linear-gradient(135deg,rgb(76,22,0),rgb(30,8,0))',kind:'rss',url:'https://dev.to/feed/tag/tensorflow' },

  // ── Blogs & writers ─────────────────────────────────────────────
  { id:'karpathy',name:'Andrej Karpathy',short:'KAR',color:'#6366f1',grad:'linear-gradient(135deg,rgb(29,20,36),rgb(11,8,14))',kind:'rss',url:'https://karpathy.github.io/feed.xml' },
  { id:'lil-log',name:'Lilian Weng',short:'LIL',color:'#ec4899',grad:'linear-gradient(135deg,rgb(59,8,36),rgb(23,3,14))',kind:'rss',url:'https://lilianweng.github.io/index.xml' },
  { id:'sebastianraschka',name:'Sebastian Raschka',short:'RAS',color:'#22c55e',grad:'linear-gradient(135deg,rgb(10,39,14),rgb(4,15,5))',kind:'rss',url:'https://sebastianraschka.com/rss_feed.xml' },
  { id:'ruder',name:'Sebastian Ruder',short:'RUD',color:'#3b82f6',grad:'linear-gradient(135deg,rgb(14,31,66),rgb(5,12,26))',kind:'rss',url:'https://www.ruder.io/rss/' },
  { id:'distillpub',name:'Distill.pub',short:'DIS',color:'#14b8a6',grad:'linear-gradient(135deg,rgb(5,37,33),rgb(2,15,13))',kind:'rss',url:'https://distill.pub/rss.xml' },
  { id:'machinelearningmastery',name:'ML Mastery',short:'MLM',color:'#0ea5e9',grad:'linear-gradient(135deg,rgb(3,31,45),rgb(1,12,18))',kind:'rss',url:'https://machinelearningmastery.com/feed/' },
  { id:'theneurond',name:'The Neuron',short:'TN',color:'#f97316',grad:'linear-gradient(135deg,rgb(74,23,3),rgb(29,9,1))',kind:'rss',url:'https://theneuron.ai/feed' },
  { id:'simonwillison',name:'Simon Willison',short:'SIM',color:'#059669',grad:'linear-gradient(135deg,rgb(2,25,13),rgb(1,10,5))',kind:'rss',url:'https://simonwillison.net/atom/everything/' },
  { id:'twiml-ai',name:'TWIML AI',short:'TWIM',color:'#6366f1',grad:'linear-gradient(135deg,rgb(29,20,36),rgb(11,8,14))',kind:'rss',url:'https://twimlai.com/feed/' },
  { id:'analyticsvidhya',name:'Analytics Vidhya',short:'AV',color:'#0077b6',grad:'linear-gradient(135deg,rgb(0,29,37),rgb(0,11,15))',kind:'rss',url:'https://www.analyticsvidhya.com/feed/' },
  { id:'towardsdatascience',name:'Towards Data Science',short:'TDS',color:'#00796b',grad:'linear-gradient(135deg,rgb(0,30,26),rgb(0,12,10))',kind:'rss',url:'https://towardsdatascience.com/feed' },

  // ── Open source projects ────────────────────────────────────────
  { id:'huggingface-blog',name:'HF Blog',short:'HF-B',color:'#ffd21e',grad:'linear-gradient(135deg,rgb(76,42,4),rgb(30,16,1))',kind:'rss',url:'https://huggingface.co/blog/feed.xml' },
  { id:'pytorch-blog',name:'PyTorch Blog',short:'PT-B',color:'#ee4c2c',grad:'linear-gradient(135deg,rgb(71,15,6),rgb(28,6,2))',kind:'rss',url:'https://pytorch.org/blog/feed.xml' },
  { id:'tensorflow-blog',name:'TensorFlow Blog',short:'TF-B',color:'#ff6f00',grad:'linear-gradient(135deg,rgb(76,22,0),rgb(30,8,0))',kind:'rss',url:'https://blog.tensorflow.org/feeds/posts/default?alt=rss' },
  { id:'ollama-blog',name:'Ollama Blog',short:'OLL-B',color:'#ffffff',grad:'linear-gradient(135deg,rgb(76,51,38),rgb(30,20,15))',kind:'rss',url:'https://ollama.com/blog/rss.xml' },
  { id:'docker-blog',name:'Docker Blog',short:'DKR',color:'#2496ed',grad:'linear-gradient(135deg,rgb(9,35,58),rgb(3,14,23))',kind:'rss',url:'https://www.docker.com/blog/feed/' },
  { id:'kubernetes-blog',name:'Kubernetes Blog',short:'K8S',color:'#326ce5',grad:'linear-gradient(135deg,rgb(12,22,49),rgb(5,9,20))',kind:'rss',url:'https://kubernetes.io/feed.xml' },
  { id:'redis-blog',name:'Redis Blog',short:'RED-B',color:'#dc382d',grad:'linear-gradient(135deg,rgb(66,11,6),rgb(26,4,2))',kind:'rss',url:'https://redis.io/blog/feed/' },
  { id:'neo4j-blog',name:'Neo4j Blog',short:'NJ',color:'#018bff',grad:'linear-gradient(135deg,rgb(0,26,55),rgb(0,10,22))',kind:'rss',url:'https://neo4j.com/blog/feed/' },
  { id:'replicate-blog',name:'Replicate Blog',short:'REP',color:'#6366f1',grad:'linear-gradient(135deg,rgb(29,20,36),rgb(11,8,14))',kind:'rss',url:'https://replicate.com/blog/rss' },
  { id:'wandb-connected',name:'W&B Connected',short:'W&B-C',color:'#ffcc33',grad:'linear-gradient(135deg,rgb(76,40,7),rgb(30,16,3))',kind:'rss',url:'https://wandb.ai/fully-connected/rss.xml' },
  { id:'weaviate-blog',name:'Weaviate Blog',short:'WV-B',color:'#22c55e',grad:'linear-gradient(135deg,rgb(10,39,14),rgb(4,15,5))',kind:'rss',url:'https://www.weaviate.io/blog/rss.xml' },
  { id:'mlflow-blog',name:'MLflow Blog',short:'MLF-B',color:'#0194e2',grad:'linear-gradient(135deg,rgb(0,29,33),rgb(0,11,13))',kind:'rss',url:'https://mlflow.org/blog/rss.xml' },

  // ── Cloud & infra ───────────────────────────────────────────────
  { id:'aws-ml',name:'AWS ML Blog',short:'AWS-B',color:'#ff9900',grad:'linear-gradient(135deg,rgb(76,30,0),rgb(30,12,0))',kind:'rss',url:'https://aws.amazon.com/blogs/machine-learning/feed/' },
  { id:'linode-ai',name:'Linode Blog',short:'LIN',color:'#00b050',grad:'linear-gradient(135deg,rgb(0,33,16),rgb(0,13,6))',kind:'rss',url:'https://www.linode.com/blog/feed/' },
  { id:'runpod-blog',name:'RunPod Blog',short:'RP',color:'#7c3aed',grad:'linear-gradient(135deg,rgb(37,11,35),rgb(14,4,14))',kind:'rss',url:'https://www.runpod.io/blog/rss.xml' },

  // ── NVIDIA ──────────────────────────────────────────────────────
  { id:'nvidia-developer',name:'NVIDIA Developer',short:'NV-D2',color:'#76b900',grad:'linear-gradient(135deg,rgb(35,37,0),rgb(14,14,0))',kind:'rss',url:'https://developer.nvidia.com/blog/feed/' },

  // ── YouTube channels ────────────────────────────────────────────
  { id:'yt-3blue1brown',name:'3Blue1Brown',short:'3B1B',color:'#1d4ed8',grad:'linear-gradient(135deg,rgb(7,14,51),rgb(3,5,20))',kind:'rss',url:'https://www.youtube.com/feeds/videos.xml?channel_id=UCYO_jab_esuFRV4b17AJtAw' },
  { id:'yt-fireship',name:'Fireship',short:'FIRE',color:'#ef4444',grad:'linear-gradient(135deg,rgb(59,8,8),rgb(23,3,3))',kind:'rss',url:'https://www.youtube.com/feeds/videos.xml?channel_id=UCsBjURrPoezykLs9EqgamOA' },
  { id:'yt-karpathy',name:'Karpathy YT',short:'K-YT',color:'#6366f1',grad:'linear-gradient(135deg,rgb(29,20,36),rgb(11,8,14))',kind:'rss',url:'https://www.youtube.com/feeds/videos.xml?channel_id=UCXUPKJO5MZQN11PqgIvyuvQ' },
  { id:'yt-ai-explained',name:'AI Explained',short:'AIE',color:'#3b82f6',grad:'linear-gradient(135deg,rgb(14,31,66),rgb(5,12,26))',kind:'rss',url:'https://www.youtube.com/feeds/videos.xml?channel_id=UCNJ1Ymd5yFuUPtn21xtRbbw' },
  { id:'yt-yannick',name:'Yannic Kilcher',short:'YK',color:'#8b5cf6',grad:'linear-gradient(135deg,rgb(41,18,36),rgb(16,7,14))',kind:'rss',url:'https://www.youtube.com/feeds/videos.xml?channel_id=UCZHmQk67mSJgfCCTn7xBfew' },

  // ── AI Safety ───────────────────────────────────────────────────
  { id:'alignment-forum',name:'Alignment Forum',short:'ALF',color:'#7c3aed',grad:'linear-gradient(135deg,rgb(37,11,35),rgb(14,4,14))',kind:'rss',url:'https://www.alignmentforum.org/feed.xml' },
  { id:'lesswrong-ai',name:'LessWrong AI',short:'LW',color:'#dc382d',grad:'linear-gradient(135deg,rgb(66,11,6),rgb(26,4,2))',kind:'rss',url:'https://www.lesswrong.com/feed.xml?tag=AI' },
  { id:'futureoflife',name:'Future of Life',short:'FLI',color:'#0ea5e9',grad:'linear-gradient(135deg,rgb(3,31,45),rgb(1,12,18))',kind:'rss',url:'https://futureoflife.org/feed/' },

  // ── Reddit communities ──────────────────────────────────────────
  { id:'reddit-localllama',name:'r/LocalLLaMA',short:'R-LLM',color:'#ff4500',grad:'linear-gradient(135deg,rgb(76,11,0),rgb(30,4,0))',kind:'rss',url:'https://www.reddit.com/r/LocalLLaMA/top/.rss?t=week' },

  // ── Lobsters tags ───────────────────────────────────────────────
  { id:'lobsters-ai',name:'Lobsters AI',short:'LOB-AI',color:'#ac3513',grad:'linear-gradient(135deg,rgb(40,12,3),rgb(16,5,1))',kind:'rss',url:'https://lobste.rs/t/ai.rss' },
  { id:'lobsters-javascript',name:'Lobsters JS',short:'LOB-JS',color:'#f7df1e',grad:'linear-gradient(135deg,rgb(60,46,0),rgb(24,18,0))',kind:'rss',url:'https://lobste.rs/t/javascript.rss' },

  // ── Google News — AI topics ─────────────────────────────────────
  { id:'gn-ai',name:'Google News: AI',short:'GN-AI',color:'#4285f4',grad:'linear-gradient(135deg,rgb(19,26,36),rgb(7,10,14))',kind:'rss',url:'https://news.google.com/rss/search?q=artificial+intelligence&hl=en-US&gl=US&ceid=US:en' },
  { id:'gn-llm',name:'Google News: LLM',short:'GN-LLM',color:'#4285f4',grad:'linear-gradient(135deg,rgb(19,26,36),rgb(7,10,14))',kind:'rss',url:'https://news.google.com/rss/search?q=large+language+model&hl=en-US&gl=US&ceid=US:en' },
  { id:'gn-gpt',name:'Google News: GPT',short:'GN-GPT',color:'#4285f4',grad:'linear-gradient(135deg,rgb(19,26,36),rgb(7,10,14))',kind:'rss',url:'https://news.google.com/rss/search?q=GPT+OpenAI&hl=en-US&gl=US&ceid=US:en' },
  { id:'gn-claude',name:'Google News: Claude',short:'GN-CLD',color:'#4285f4',grad:'linear-gradient(135deg,rgb(19,26,36),rgb(7,10,14))',kind:'rss',url:'https://news.google.com/rss/search?q=Claude+Anthropic&hl=en-US&gl=US&ceid=US:en' },
  { id:'gn-gemini',name:'Google News: Gemini',short:'GN-GEM',color:'#4285f4',grad:'linear-gradient(135deg,rgb(19,26,36),rgb(7,10,14))',kind:'rss',url:'https://news.google.com/rss/search?q=Gemini+Google+AI&hl=en-US&gl=US&ceid=US:en' },
  { id:'gn-llama',name:'Google News: Llama',short:'GN-LLM',color:'#4285f4',grad:'linear-gradient(135deg,rgb(19,26,36),rgb(7,10,14))',kind:'rss',url:'https://news.google.com/rss/search?q=Llama+Meta+AI+open+source&hl=en-US&gl=US&ceid=US:en' },
  { id:'gn-deepseek',name:'Google News: DeepSeek',short:'GN-DS',color:'#4285f4',grad:'linear-gradient(135deg,rgb(19,26,36),rgb(7,10,14))',kind:'rss',url:'https://news.google.com/rss/search?q=DeepSeek+AI&hl=en-US&gl=US&ceid=US:en' },
  { id:'gn-robotics',name:'Google News: Robotics',short:'GN-RBT',color:'#4285f4',grad:'linear-gradient(135deg,rgb(19,26,36),rgb(7,10,14))',kind:'rss',url:'https://news.google.com/rss/search?q=AI+robotics&hl=en-US&gl=US&ceid=US:en' },
  { id:'gn-ai-chips',name:'Google News: AI Chips',short:'GN-CHP',color:'#4285f4',grad:'linear-gradient(135deg,rgb(19,26,36),rgb(7,10,14))',kind:'rss',url:'https://news.google.com/rss/search?q=AI+chips+GPU+NVIDIA&hl=en-US&gl=US&ceid=US:en' },
  { id:'gn-ai-safety',name:'Google News: AI Safety',short:'GN-SAF',color:'#4285f4',grad:'linear-gradient(135deg,rgb(19,26,36),rgb(7,10,14))',kind:'rss',url:'https://news.google.com/rss/search?q=AI+safety+alignment&hl=en-US&gl=US&ceid=US:en' },
  { id:'gn-ai-startups',name:'Google News: AI Startups',short:'GN-ST',color:'#4285f4',grad:'linear-gradient(135deg,rgb(19,26,36),rgb(7,10,14))',kind:'rss',url:'https://news.google.com/rss/search?q=AI+startup+funding&hl=en-US&gl=US&ceid=US:en' },
  { id:'gn-ai-regulation',name:'Google News: AI Policy',short:'GN-REG',color:'#4285f4',grad:'linear-gradient(135deg,rgb(19,26,36),rgb(7,10,14))',kind:'rss',url:'https://news.google.com/rss/search?q=AI+regulation+policy&hl=en-US&gl=US&ceid=US:en' },
  { id:'gn-open-source-ai',name:'Google News: OSS AI',short:'GN-OSS',color:'#4285f4',grad:'linear-gradient(135deg,rgb(19,26,36),rgb(7,10,14))',kind:'rss',url:'https://news.google.com/rss/search?q=open+source+AI+model&hl=en-US&gl=US&ceid=US:en' },
  { id:'gn-ai-video',name:'Google News: AI Video',short:'GN-VID',color:'#4285f4',grad:'linear-gradient(135deg,rgb(19,26,36),rgb(7,10,14))',kind:'rss',url:'https://news.google.com/rss/search?q=AI+video+Sora+Runway&hl=en-US&gl=US&ceid=US:en' },
  { id:'gn-ai-audio',name:'Google News: AI Audio',short:'GN-AUD',color:'#4285f4',grad:'linear-gradient(135deg,rgb(19,26,36),rgb(7,10,14))',kind:'rss',url:'https://news.google.com/rss/search?q=AI+audio+voice+music&hl=en-US&gl=US&ceid=US:en' },
  { id:'gn-ai-image',name:'Google News: AI Image',short:'GN-IMG',color:'#4285f4',grad:'linear-gradient(135deg,rgb(19,26,36),rgb(7,10,14))',kind:'rss',url:'https://news.google.com/rss/search?q=AI+image+generation+DALL-E&hl=en-US&gl=US&ceid=US:en' },
  { id:'gn-ai-code',name:'Google News: AI Code',short:'GN-COD',color:'#4285f4',grad:'linear-gradient(135deg,rgb(19,26,36),rgb(7,10,14))',kind:'rss',url:'https://news.google.com/rss/search?q=AI+coding+copilot&hl=en-US&gl=US&ceid=US:en' },
  { id:'gn-openai-blog',name:'GN: OpenAI Blog',short:'GN-OAI',color:'#4285f4',grad:'linear-gradient(135deg,rgb(19,26,36),rgb(7,10,14))',kind:'rss',url:'https://news.google.com/rss/search?q=site:openai.com&hl=en-US&gl=US&ceid=US:en' },
  { id:'gn-anthropic-blog',name:'GN: Anthropic Blog',short:'GN-ANT',color:'#4285f4',grad:'linear-gradient(135deg,rgb(19,26,36),rgb(7,10,14))',kind:'rss',url:'https://news.google.com/rss/search?q=site:anthropic.com&hl=en-US&gl=US&ceid=US:en' },
  { id:'gn-google-ai',name:'GN: Google AI',short:'GN-GAI',color:'#4285f4',grad:'linear-gradient(135deg,rgb(19,26,36),rgb(7,10,14))',kind:'rss',url:'https://news.google.com/rss/search?q=site:ai.google+OR+site:deepmind.google&hl=en-US&gl=US&ceid=US:en' },
  { id:'gn-meta-ai',name:'GN: Meta AI',short:'GN-MET',color:'#4285f4',grad:'linear-gradient(135deg,rgb(19,26,36),rgb(7,10,14))',kind:'rss',url:'https://news.google.com/rss/search?q=site:ai.meta.com&hl=en-US&gl=US&ceid=US:en' },
  { id:'gn-microsoft-ai',name:'GN: Microsoft AI',short:'GN-MS',color:'#4285f4',grad:'linear-gradient(135deg,rgb(19,26,36),rgb(7,10,14))',kind:'rss',url:'https://news.google.com/rss/search?q=site:microsoft.com+AI+OR+copilot&hl=en-US&gl=US&ceid=US:en' },
  { id:'gn-qwen',name:'Google News: Qwen',short:'GN-QW',color:'#4285f4',grad:'linear-gradient(135deg,rgb(19,26,36),rgb(7,10,14))',kind:'rss',url:'https://news.google.com/rss/search?q=Qwen+AI+model&hl=en-US&gl=US&ceid=US:en' },
  { id:'gn-grok',name:'Google News: Grok',short:'GN-GRK',color:'#4285f4',grad:'linear-gradient(135deg,rgb(19,26,36),rgb(7,10,14))',kind:'rss',url:'https://news.google.com/rss/search?q=Grok+xAI&hl=en-US&gl=US&ceid=US:en' },
  { id:'gn-mistral',name:'Google News: Mistral',short:'GN-MIS',color:'#4285f4',grad:'linear-gradient(135deg,rgb(19,26,36),rgb(7,10,14))',kind:'rss',url:'https://news.google.com/rss/search?q=Mistral+AI&hl=en-US&gl=US&ceid=US:en' },
  { id:'gn-huggingface',name:'Google News: HF',short:'GN-HF',color:'#4285f4',grad:'linear-gradient(135deg,rgb(19,26,36),rgb(7,10,14))',kind:'rss',url:'https://news.google.com/rss/search?q=HuggingFace+AI&hl=en-US&gl=US&ceid=US:en' },
  { id:'gn-ollama',name:'Google News: Ollama',short:'GN-OLL',color:'#4285f4',grad:'linear-gradient(135deg,rgb(19,26,36),rgb(7,10,14))',kind:'rss',url:'https://news.google.com/rss/search?q=Ollama+local+LLM&hl=en-US&gl=US&ceid=US:en' },
  { id:'gn-rag',name:'Google News: RAG',short:'GN-RAG',color:'#4285f4',grad:'linear-gradient(135deg,rgb(19,26,36),rgb(7,10,14))',kind:'rss',url:'https://news.google.com/rss/search?q=RAG+retrieval+augmented+generation&hl=en-US&gl=US&ceid=US:en' },
  { id:'gn-agents',name:'Google News: Agents',short:'GN-AGT',color:'#4285f4',grad:'linear-gradient(135deg,rgb(19,26,36),rgb(7,10,14))',kind:'rss',url:'https://news.google.com/rss/search?q=AI+agents+autonomous&hl=en-US&gl=US&ceid=US:en' },
  { id:'gn-fine-tuning',name:'Google News: Fine-tuning',short:'GN-FT',color:'#4285f4',grad:'linear-gradient(135deg,rgb(19,26,36),rgb(7,10,14))',kind:'rss',url:'https://news.google.com/rss/search?q=AI+fine+tuning+training&hl=en-US&gl=US&ceid=US:en' },
  { id:'gn-multimodal',name:'Google News: Multimodal',short:'GN-MM',color:'#4285f4',grad:'linear-gradient(135deg,rgb(19,26,36),rgb(7,10,14))',kind:'rss',url:'https://news.google.com/rss/search?q=multimodal+AI+vision&hl=en-US&gl=US&ceid=US:en' },
  { id:'gn-benchmark',name:'Google News: Benchmarks',short:'GN-BEN',color:'#4285f4',grad:'linear-gradient(135deg,rgb(19,26,36),rgb(7,10,14))',kind:'rss',url:'https://news.google.com/rss/search?q=AI+benchmark+leaderboard&hl=en-US&gl=US&ceid=US:en' },

  // ── Hacker News more ────────────────────────────────────────────
  { id:'hn-llm',name:'HN LLM',short:'HN-L',color:'#ff6600',grad:'linear-gradient(135deg,rgb(76,20,0),rgb(30,8,0))',kind:'rss',url:'https://hnrss.org/newest?q=LLM+OR+language+model&points=50' },
  { id:'hn-ml',name:'HN ML',short:'HN-M',color:'#ff6600',grad:'linear-gradient(135deg,rgb(76,20,0),rgb(30,8,0))',kind:'rss',url:'https://hnrss.org/newest?q=machine+learning+OR+deep+learning&points=50' },

  // ── TechCrunch ──────────────────────────────────────────────────
  { id:'techcrunch-ai',name:'TechCrunch AI',short:'TC-AI',color:'#00a562',grad:'linear-gradient(135deg,rgb(0,33,19),rgb(0,13,7))',kind:'rss',url:'https://techcrunch.com/category/artificial-intelligence/feed/' },
  { id:'techcrunch-robotics',name:'TechCrunch Robotics',short:'TC-R',color:'#00a562',grad:'linear-gradient(135deg,rgb(0,33,19),rgb(0,13,7))',kind:'rss',url:'https://techcrunch.com/category/robotics/feed/' },
  { id:'techcrunch-venture',name:'TechCrunch Venture',short:'TC-V',color:'#00a562',grad:'linear-gradient(135deg,rgb(0,33,19),rgb(0,13,7))',kind:'rss',url:'https://techcrunch.com/category/venture/feed/' },

  // ── Product Hunt ────────────────────────────────────────────────
  { id:'ph-ai',name:'Product Hunt AI',short:'PH',color:'#da552f',grad:'linear-gradient(135deg,rgb(54,16,8),rgb(21,6,3))',kind:'rss',url:'https://www.producthunt.com/feed?category=ai' },

  // ── Science ─────────────────────────────────────────────────────
  { id:'sciencedaily-ai',name:'ScienceDaily AI',short:'SD',color:'#006400',grad:'linear-gradient(135deg,rgb(0,25,0),rgb(0,10,0))',kind:'rss',url:'https://www.sciencedaily.com/rss/computers_math/artificial_intelligence.xml' },
  { id:'quantamagazine',name:'Quanta Magazine',short:'QNT',color:'#1a1a2e',grad:'linear-gradient(135deg,rgb(5,5,12),rgb(2,2,5))',kind:'rss',url:'https://www.quantamagazine.org/feed/' },

  // ── Medium tags ─────────────────────────────────────────────────
  { id:'medium-datascience',name:'Medium DataScience',short:'MED-DS',color:'#00796b',grad:'linear-gradient(135deg,rgb(0,30,26),rgb(0,12,10))',kind:'rss',url:'https://medium.com/feed/tag/data-science' },

  // ── Stack Overflow ──────────────────────────────────────────────
  { id:'stackoverflow-llm',name:'SO LLM',short:'SO-L',color:'#f48024',grad:'linear-gradient(135deg,rgb(61,25,5),rgb(24,10,2))',kind:'rss',url:'https://stackoverflow.com/feeds/tag/large-language-model' },
  { id:'stackoverflow-nlp',name:'SO NLP',short:'SO-N',color:'#f48024',grad:'linear-gradient(135deg,rgb(61,25,5),rgb(24,10,2))',kind:'rss',url:'https://stackoverflow.com/feeds/tag/nlp' },

  // ── More blogs ──────────────────────────────────────────────────
  { id:'datarobot-blog',name:'DataRobot',short:'DR',color:'#1b2a4a',grad:'linear-gradient(135deg,rgb(6,10,18),rgb(2,4,7))',kind:'rss',url:'https://www.datarobot.com/blog/feed/' },
  { id:'analytics-india',name:'Analytics India',short:'AI-M',color:'#e63946',grad:'linear-gradient(135deg,rgb(58,14,17),rgb(23,5,7))',kind:'rss',url:'https://analyticsindiamag.com/category/artificial-intelligence/feed/' },

  // ── Regional AI (Asia, Europe, Global) ──────────────────────────
  { id:'china-ai',name:'China AI News',short:'CNAI',color:'#dc2626',grad:'linear-gradient(135deg,rgb(55,8,8),rgb(22,3,3))',kind:'rss',url:'https://news.google.com/rss/search?q=China+AI+artificial+intelligence&hl=en-US&gl=US&ceid=US:en' },
  { id:'japan-ai',name:'Japan AI News',short:'JAI',color:'#2563eb',grad:'linear-gradient(135deg,rgb(8,15,46),rgb(3,6,18))',kind:'rss',url:'https://news.google.com/rss/search?q=Japan+AI+artificial+intelligence&hl=en-US&gl=US&ceid=US:en' },
  { id:'korea-ai',name:'Korea AI News',short:'KAI',color:'#7c3aed',grad:'linear-gradient(135deg,rgb(37,11,35),rgb(14,4,14))',kind:'rss',url:'https://news.google.com/rss/search?q=Korea+AI+artificial+intelligence&hl=en-US&gl=US&ceid=US:en' },
  { id:'india-ai',name:'India AI News',short:'IAI',color:'#f59e0b',grad:'linear-gradient(135deg,rgb(61,24,2),rgb(24,9,1))',kind:'rss',url:'https://news.google.com/rss/search?q=India+AI+artificial+intelligence&hl=en-US&gl=US&ceid=US:en' },
  { id:'eu-ai',name:'EU AI Policy',short:'EUAI',color:'#1d4ed8',grad:'linear-gradient(135deg,rgb(7,14,51),rgb(3,5,20))',kind:'rss',url:'https://news.google.com/rss/search?q=EU+Europe+AI+regulation&hl=en-US&gl=US&ceid=US:en' },
  { id:'uk-ai',name:'UK AI News',short:'UKAI',color:'#1e3a5f',grad:'linear-gradient(135deg,rgb(7,14,24),rgb(3,5,10))',kind:'rss',url:'https://news.google.com/rss/search?q=UK+AI+artificial+intelligence&hl=en-US&gl=US&ceid=US:en' },
  { id:'germany-ai',name:'Germany AI',short:'DEAI',color:'#6b7280',grad:'linear-gradient(135deg,rgb(30,30,30),rgb(12,12,12))',kind:'rss',url:'https://news.google.com/rss/search?q=Germany+AI+artificial+intelligence&hl=en-US&gl=US&ceid=US:en' },
  { id:'kr-asia',name:'KR Asia',short:'KR',color:'#dc2626',grad:'linear-gradient(135deg,rgb(55,8,8),rgb(22,3,3))',kind:'rss',url:'https://kr-asia.com/feed' },
  { id:'techinasia',name:'Tech in Asia',short:'TIA',color:'#1d4ed8',grad:'linear-gradient(135deg,rgb(7,14,51),rgb(3,5,20))',kind:'rss',url:'https://www.techinasia.com/feed' },
  { id:'techcrunch-africa',name:'TC Africa',short:'TC-AF',color:'#00a562',grad:'linear-gradient(135deg,rgb(0,33,19),rgb(0,13,7))',kind:'rss',url:'https://techcrunch.com/tag/africa/feed/' },

  // ── Google News deep topic feeds ────────────────────────────────
  { id:'gn-ai-agent',name:'GN: AI Agents',short:'GN-AG',color:'#059669',grad:'linear-gradient(135deg,rgb(2,25,13),rgb(1,10,5))',kind:'rss',url:'https://news.google.com/rss/search?q=AI+agent+framework+LangChain+CrewAI&hl=en-US&gl=US&ceid=US:en' },
  { id:'gn-ai-testing',name:'GN: AI Testing',short:'GN-TST',color:'#dc2626',grad:'linear-gradient(135deg,rgb(55,8,8),rgb(22,3,3))',kind:'rss',url:'https://news.google.com/rss/search?q=AI+testing+evaluation+benchmark&hl=en-US&gl=US&ceid=US:en' },
  { id:'gn-ai-hardware',name:'GN: AI Hardware',short:'GN-HW',color:'#76b900',grad:'linear-gradient(135deg,rgb(35,37,0),rgb(14,14,0))',kind:'rss',url:'https://news.google.com/rss/search?q=AI+hardware+TPU+ASIC&hl=en-US&gl=US&ceid=US:en' },
  { id:'gn-ai-open-source',name:'GN: AI Open Source',short:'GN-OSS2',color:'#059669',grad:'linear-gradient(135deg,rgb(2,25,13),rgb(1,10,5))',kind:'rss',url:'https://news.google.com/rss/search?q=AI+open+source+Apache+MIT+license&hl=en-US&gl=US&ceid=US:en' },
  { id:'gn-ai-privacy',name:'GN: AI Privacy',short:'GN-PRI',color:'#7c3aed',grad:'linear-gradient(135deg,rgb(37,11,35),rgb(14,4,14))',kind:'rss',url:'https://news.google.com/rss/search?q=AI+privacy+differential+federated&hl=en-US&gl=US&ceid=US:en' },
  { id:'gn-ai-medical',name:'GN: AI Medical',short:'GN-MED',color:'#22c55e',grad:'linear-gradient(135deg,rgb(10,39,14),rgb(4,15,5))',kind:'rss',url:'https://news.google.com/rss/search?q=AI+medical+healthcare+diagnosis&hl=en-US&gl=US&ceid=US:en' },
  { id:'gn-ai-finance',name:'GN: AI Finance',short:'GN-FIN',color:'#f59e0b',grad:'linear-gradient(135deg,rgb(61,24,2),rgb(24,9,1))',kind:'rss',url:'https://news.google.com/rss/search?q=AI+finance+trading+quant&hl=en-US&gl=US&ceid=US:en' },
  { id:'gn-ai-education',name:'GN: AI Education',short:'GN-EDU',color:'#3b82f6',grad:'linear-gradient(135deg,rgb(14,31,66),rgb(5,12,26))',kind:'rss',url:'https://news.google.com/rss/search?q=AI+education+tutoring+learning&hl=en-US&gl=US&ceid=US:en' },
  { id:'gn-ai-autonomous',name:'GN: AI Autonomous',short:'GN-AUTO',color:'#06b6d4',grad:'linear-gradient(135deg,rgb(2,37,46),rgb(1,14,18))',kind:'rss',url:'https://news.google.com/rss/search?q=AI+autonomous+driving+vehicles&hl=en-US&gl=US&ceid=US:en' },
  { id:'gn-ai-3d',name:'GN: AI 3D Gen',short:'GN-3D',color:'#ec4899',grad:'linear-gradient(135deg,rgb(59,8,36),rgb(23,3,14))',kind:'rss',url:'https://news.google.com/rss/search?q=AI+3D+generation+NeRF+gaussian&hl=en-US&gl=US&ceid=US:en' },
  { id:'gn-ai-protein',name:'GN: AI Protein',short:'GN-PROT',color:'#14b8a6',grad:'linear-gradient(135deg,rgb(5,37,33),rgb(2,15,13))',kind:'rss',url:'https://news.google.com/rss/search?q=AI+protein+folding+bio+AlphaFold&hl=en-US&gl=US&ceid=US:en' },
  { id:'gn-ai-game',name:'GN: AI Gaming',short:'GN-GAME',color:'#f97316',grad:'linear-gradient(135deg,rgb(74,23,3),rgb(29,9,1))',kind:'rss',url:'https://news.google.com/rss/search?q=AI+gaming+gameplay+NPC&hl=en-US&gl=US&ceid=US:en' },
  { id:'gn-ai-cyber',name:'GN: AI Cybersec',short:'GN-CYB',color:'#ef4444',grad:'linear-gradient(135deg,rgb(59,8,8),rgb(23,3,3))',kind:'rss',url:'https://news.google.com/rss/search?q=AI+cybersecurity+threat+detection&hl=en-US&gl=US&ceid=US:en' },
  { id:'gn-ai-climate',name:'GN: AI Climate',short:'GN-CLIM',color:'#10b981',grad:'linear-gradient(135deg,rgb(4,39,23),rgb(1,15,9))',kind:'rss',url:'https://news.google.com/rss/search?q=AI+climate+weather+environment&hl=en-US&gl=US&ceid=US:en' },
  { id:'gn-ai-hallucination',name:'GN: AI Hallucination',short:'GN-HAL',color:'#e11d48',grad:'linear-gradient(135deg,rgb(57,7,18),rgb(22,3,7))',kind:'rss',url:'https://news.google.com/rss/search?q=AI+hallucination+faithfulness+grounding&hl=en-US&gl=US&ceid=US:en' },
  { id:'gn-ai-distillation',name:'GN: AI Distill',short:'GN-DIST',color:'#8b5cf6',grad:'linear-gradient(135deg,rgb(41,18,36),rgb(16,7,14))',kind:'rss',url:'https://news.google.com/rss/search?q=AI+distillation+quantization+compression&hl=en-US&gl=US&ceid=US:en' },
  { id:'gn-ai-agi',name:'GN: AGI',short:'GN-AGI',color:'#dc2626',grad:'linear-gradient(135deg,rgb(55,8,8),rgb(22,3,3))',kind:'rss',url:'https://news.google.com/rss/search?q=AGI+artificial+general+intelligence&hl=en-US&gl=US&ceid=US:en' },
  { id:'gn-ai-spaces',name:'GN: AI Infra',short:'GN-INFRA',color:'#0ea5e9',grad:'linear-gradient(135deg,rgb(3,31,45),rgb(1,12,18))',kind:'rss',url:'https://news.google.com/rss/search?q=AI+spaces+infrastructure+datacenter&hl=en-US&gl=US&ceid=US:en' },
  { id:'gn-ai-chips-nvidia',name:'GN: NVIDIA Chips',short:'GN-NV2',color:'#76b900',grad:'linear-gradient(135deg,rgb(35,37,0),rgb(14,14,0))',kind:'rss',url:'https://news.google.com/rss/search?q=NVIDIA+H100+B200+Blackwell&hl=en-US&gl=US&ceid=US:en' },
  { id:'gn-ai-chips-amd',name:'GN: AMD AI Chips',short:'GN-AMD',color:'#dc2626',grad:'linear-gradient(135deg,rgb(55,8,8),rgb(22,3,3))',kind:'rss',url:'https://news.google.com/rss/search?q=AMD+MI300+AI+chip&hl=en-US&gl=US&ceid=US:en' },
  { id:'gn-ai-chips-intel',name:'GN: Intel AI Chips',short:'GN-INT',color:'#0071c5',grad:'linear-gradient(135deg,rgb(0,22,42),rgb(0,9,17))',kind:'rss',url:'https://news.google.com/rss/search?q=Intel+Gaudi+AI+chip&hl=en-US&gl=US&ceid=US:en' },
  { id:'gn-ai-chips-google',name:'GN: Google TPU',short:'GN-TPU',color:'#4285f4',grad:'linear-gradient(135deg,rgb(19,26,36),rgb(7,10,14))',kind:'rss',url:'https://news.google.com/rss/search?q=Google+TPU+Trillium&hl=en-US&gl=US&ceid=US:en' },
  { id:'gn-ai-training',name:'GN: AI Training',short:'GN-TRN',color:'#f97316',grad:'linear-gradient(135deg,rgb(74,23,3),rgb(29,9,1))',kind:'rss',url:'https://news.google.com/rss/search?q=AI+training+compute+scaling&hl=en-US&gl=US&ceid=US:en' },
  { id:'gn-ai-inference',name:'GN: AI Inference',short:'GN-INF2',color:'#06b6d4',grad:'linear-gradient(135deg,rgb(2,37,46),rgb(1,14,18))',kind:'rss',url:'https://news.google.com/rss/search?q=AI+inference+serving+optimization&hl=en-US&gl=US&ceid=US:en' },
  { id:'gn-ai-embedding',name:'GN: AI Embeddings',short:'GN-EMB',color:'#6366f1',grad:'linear-gradient(135deg,rgb(29,20,36),rgb(11,8,14))',kind:'rss',url:'https://news.google.com/rss/search?q=AI+embedding+vector+search&hl=en-US&gl=US&ceid=US:en' },
  { id:'gn-ai-regulation-eu',name:'GN: EU AI Act',short:'GN-EUA',color:'#1d4ed8',grad:'linear-gradient(135deg,rgb(7,14,51),rgb(3,5,20))',kind:'rss',url:'https://news.google.com/rss/search?q=EU+AI+Act+regulation&hl=en-US&gl=US&ceid=US:en' },
  { id:'gn-ai-regulation-us',name:'GN: US AI Policy',short:'GN-USP',color:'#1e3a5f',grad:'linear-gradient(135deg,rgb(7,14,24),rgb(3,5,10))',kind:'rss',url:'https://news.google.com/rss/search?q=US+AI+executive+order+regulation&hl=en-US&gl=US&ceid=US:en' },
  { id:'gn-ai-china',name:'GN: China AI',short:'GN-CHN',color:'#dc2626',grad:'linear-gradient(135deg,rgb(55,8,8),rgb(22,3,3))',kind:'rss',url:'https://news.google.com/rss/search?q=China+AI+DeepSeek+Baidu+Alibaba&hl=en-US&gl=US&ceid=US:en' },

  // ── Dev.to more tags ────────────────────────────────────────────
  { id:'devto-claude',name:'DEV Claude',short:'DEV-C',color:'#c084fc',grad:'linear-gradient(135deg,rgb(48,13,48),rgb(19,5,19))',kind:'rss',url:'https://dev.to/feed/tag/claude' },
  { id:'devto-gemini',name:'DEV Gemini',short:'DEV-G',color:'#4285f4',grad:'linear-gradient(135deg,rgb(19,26,36),rgb(7,10,14))',kind:'rss',url:'https://dev.to/feed/tag/gemini' },
  { id:'devto-openai',name:'DEV OpenAI',short:'DEV-OAI',color:'#10a37f',grad:'linear-gradient(135deg,rgb(4,32,19),rgb(1,13,7))',kind:'rss',url:'https://dev.to/feed/tag/openai' },
  { id:'devto-robotics',name:'DEV Robotics',short:'DEV-RBT',color:'#f97316',grad:'linear-gradient(135deg,rgb(74,23,3),rgb(29,9,1))',kind:'rss',url:'https://dev.to/feed/tag/robotics' },
  { id:'devto-computervision',name:'DEV ComputerVision',short:'DEV-CV',color:'#06b6d4',grad:'linear-gradient(135deg,rgb(2,37,46),rgb(1,14,18))',kind:'rss',url:'https://dev.to/feed/tag/computervision' },
  { id:'devto-rl',name:'DEV RL',short:'DEV-RL',color:'#22c55e',grad:'linear-gradient(135deg,rgb(10,39,14),rgb(4,15,5))',kind:'rss',url:'https://dev.to/feed/tag/reinforcementlearning' },
  { id:'devto-keras',name:'DEV Keras',short:'DEV-K',color:'#d946ef',grad:'linear-gradient(135deg,rgb(54,13,51),rgb(21,5,20))',kind:'rss',url:'https://dev.to/feed/tag/keras' },
  { id:'devto-jax',name:'DEV JAX',short:'DEV-JAX',color:'#3b82f6',grad:'linear-gradient(135deg,rgb(14,31,66),rgb(5,12,26))',kind:'rss',url:'https://dev.to/feed/tag/jax' },
  { id:'devto-langchain',name:'DEV LangChain',short:'DEV-LC',color:'#22c55e',grad:'linear-gradient(135deg,rgb(10,39,14),rgb(4,15,5))',kind:'rss',url:'https://dev.to/feed/tag/langchain' },
  { id:'devto-rag',name:'DEV RAG',short:'DEV-RAG',color:'#6366f1',grad:'linear-gradient(135deg,rgb(29,20,36),rgb(11,8,14))',kind:'rss',url:'https://dev.to/feed/tag/rag' },

  // ── GitHub topic feeds ──────────────────────────────────────────
  { id:'gh-ai-llm',name:'GH: Large LLMs',short:'GH-LLM',color:'#3b82f6',grad:'linear-gradient(135deg,rgb(14,31,66),rgb(5,12,26))',kind:'rss',url:'https://github.com/topics/large-language-models.atom' },
  { id:'gh-ai-agents',name:'GH: AI Agents',short:'GH-AGT',color:'#059669',grad:'linear-gradient(135deg,rgb(2,25,13),rgb(1,10,5))',kind:'rss',url:'https://github.com/topics/ai-agents.atom' },
  { id:'gh-ai-rag',name:'GH: RAG',short:'GH-RAG',color:'#8b5cf6',grad:'linear-gradient(135deg,rgb(41,18,36),rgb(16,7,14))',kind:'rss',url:'https://github.com/topics/retrieval-augmented-generation.atom' },
  { id:'gh-stable-diffusion',name:'GH: StableDiffusion',short:'GH-SD',color:'#d946ef',grad:'linear-gradient(135deg,rgb(54,13,51),rgb(21,5,20))',kind:'rss',url:'https://github.com/topics/stable-diffusion.atom' },
  { id:'gh-machine-learning',name:'GH: ML',short:'GH-ML2',color:'#22c55e',grad:'linear-gradient(135deg,rgb(10,39,14),rgb(4,15,5))',kind:'rss',url:'https://github.com/topics/machine-learning.atom' },
  { id:'gh-deep-learning',name:'GH: DL',short:'GH-DL',color:'#ef4444',grad:'linear-gradient(135deg,rgb(59,8,8),rgb(23,3,3))',kind:'rss',url:'https://github.com/topics/deep-learning.atom' },
  { id:'gh-transformers',name:'GH: Transformers',short:'GH-TF2',color:'#f97316',grad:'linear-gradient(135deg,rgb(74,23,3),rgb(29,9,1))',kind:'rss',url:'https://github.com/topics/transformers.atom' },
  { id:'gh-nlp',name:'GH: NLP',short:'GH-NLP',color:'#ec4899',grad:'linear-gradient(135deg,rgb(59,8,36),rgb(23,3,14))',kind:'rss',url:'https://github.com/topics/natural-language-processing.atom' },
  { id:'gh-computer-vision',name:'GH: ComputerVision',short:'GH-CV',color:'#06b6d4',grad:'linear-gradient(135deg,rgb(2,37,46),rgb(1,14,18))',kind:'rss',url:'https://github.com/topics/computer-vision.atom' },
  { id:'gh-reinforcement-learning',name:'GH: RL',short:'GH-RL',color:'#14b8a6',grad:'linear-gradient(135deg,rgb(5,37,33),rgb(2,15,13))',kind:'rss',url:'https://github.com/topics/reinforcement-learning.atom' },
  { id:'gh-pytorch',name:'GH: PyTorch',short:'GH-PT',color:'#ee4c2c',grad:'linear-gradient(135deg,rgb(71,15,6),rgb(28,6,2))',kind:'rss',url:'https://github.com/topics/pytorch.atom' },
  { id:'gh-tensorflow',name:'GH: TensorFlow',short:'GH-TF3',color:'#ff6f00',grad:'linear-gradient(135deg,rgb(76,22,0),rgb(30,8,0))',kind:'rss',url:'https://github.com/topics/tensorflow.atom' },

  // ── Blogs & newsletters ─────────────────────────────────────────
  { id:'mit-news-ai',name:'MIT AI News',short:'MIT',color:'#a31f34',grad:'linear-gradient(135deg,rgb(41,7,13),rgb(16,3,5))',kind:'rss',url:'https://news.mit.edu/topic/mitartificial-intelligence2-rss.xml' },
  { id:'latentspace',name:'Latent Space',short:'LS',color:'#6366f1',grad:'linear-gradient(135deg,rgb(29,20,36),rgb(11,8,14))',kind:'rss',url:'https://www.latent.space/feed' },
  { id:'stratechery',name:'Stratechery',short:'STR',color:'#6b7280',grad:'linear-gradient(135deg,rgb(30,30,30),rgb(12,12,12))',kind:'rss',url:'https://stratechery.com/feed/' },
  { id:'exponential-view',name:'Exponential View',short:'XV',color:'#7c3aed',grad:'linear-gradient(135deg,rgb(37,11,35),rgb(14,4,14))',kind:'rss',url:'https://www.exponentialview.co/feed' },

  // ── GitHub release feeds ────────────────────────────────────────
  { id:'automatic1111',name:'Automatic1111',short:'A1111',color:'#d946ef',grad:'linear-gradient(135deg,rgb(54,13,51),rgb(21,5,20))',kind:'rss',url:'https://github.com/AUTOMATIC1111/stable-diffusion-webui/releases.atom' },
  { id:'comfyui-rss',name:'ComfyUI',short:'CMFUI',color:'#22c55e',grad:'linear-gradient(135deg,rgb(10,39,14),rgb(4,15,5))',kind:'rss',url:'https://github.com/comfyanonymous/ComfyUI/releases.atom' },
  { id:'llama-cpp',name:'llama.cpp',short:'LCPP',color:'#06b6d4',grad:'linear-gradient(135deg,rgb(2,37,46),rgb(1,14,18))',kind:'rss',url:'https://github.com/ggerganov/llama.cpp/releases.atom' },
  { id:'bento-ml',name:'BentoML',short:'BENTO',color:'#6366f1',grad:'linear-gradient(135deg,rgb(29,20,36),rgb(11,8,14))',kind:'rss',url:'https://github.com/bentoml/BentoML/releases.atom' },

  // ── Reddit more ─────────────────────────────────────────────────
  { id:'reddit-artificial',name:'r/artificial',short:'R-AI',color:'#ff4500',grad:'linear-gradient(135deg,rgb(76,11,0),rgb(30,4,0))',kind:'rss',url:'https://www.reddit.com/r/artificial/top/.rss?t=week' },

  // ── HN more ─────────────────────────────────────────────────────
  { id:'hn-openai',name:'HN: OpenAI',short:'HN-OAI',color:'#ff6600',grad:'linear-gradient(135deg,rgb(76,20,0),rgb(30,8,0))',kind:'rss',url:'https://hnrss.org/newest?q=OpenAI+GPT&points=50' },
  { id:'hn-anthropic',name:'HN: Anthropic',short:'HN-ANT',color:'#ff6600',grad:'linear-gradient(135deg,rgb(76,20,0),rgb(30,8,0))',kind:'rss',url:'https://hnrss.org/newest?q=Anthropic+Claude&points=50' },
  { id:'hn-local-llm',name:'HN: Local LLM',short:'HN-LLM',color:'#ff6600',grad:'linear-gradient(135deg,rgb(76,20,0),rgb(30,8,0))',kind:'rss',url:'https://hnrss.org/newest?q=local+LLM+Ollama+llama.cpp&points=30' },

  // ── Medium more tags ────────────────────────────────────────────
  { id:'medium-ai-agents',name:'Medium: AI Agents',short:'MED-AG',color:'#059669',grad:'linear-gradient(135deg,rgb(2,25,13),rgb(1,10,5))',kind:'rss',url:'https://medium.com/feed/tag/ai-agents' },
  { id:'medium-fine-tuning',name:'Medium: Fine-tuning',short:'MED-FT',color:'#f97316',grad:'linear-gradient(135deg,rgb(74,23,3),rgb(29,9,1))',kind:'rss',url:'https://medium.com/feed/tag/fine-tuning' },
  { id:'medium-computer-vision',name:'Medium: ComputerVision',short:'MED-CV',color:'#06b6d4',grad:'linear-gradient(135deg,rgb(2,37,46),rgb(1,14,18))',kind:'rss',url:'https://medium.com/feed/tag/computer-vision' },
  { id:'medium-vector-db',name:'Medium: Vector DB',short:'MED-VDB',color:'#8b5cf6',grad:'linear-gradient(135deg,rgb(41,18,36),rgb(16,7,14))',kind:'rss',url:'https://medium.com/feed/tag/vector-database' },
];

export const srcById: Record<string, Source> = {};
for (const s of SOURCES) srcById[s.id] = s;
