-- Seed built-in sources + benchmarks. Idempotent (ON CONFLICT DO NOTHING).

insert into public.sources (id, name, short, color, grad, kind, url) values
  ('openai', 'OpenAI', 'OAI', '#10a37f', 'linear-gradient(135deg,#0e3f33,#071d18)', 'rss', 'https://openai.com/news/rss.xml'),
  ('googleai', 'Google AI', 'GAI', '#4285F4', 'linear-gradient(135deg,#122a5e,#0a1630)', 'rss', 'https://blog.google/technology/ai/rss/'),
  ('deepmind', 'Google DeepMind', 'GDM', '#7c6cf0', 'linear-gradient(135deg,#2b2160,#120e30)', 'rss', 'https://deepmind.google/blog/rss.xml'),
  ('huggingface', 'Hugging Face', 'HF', '#ffd21e', 'linear-gradient(135deg,#4d3f06,#211b02)', 'rss', 'https://huggingface.co/blog/feed.xml'),
  ('microsoft', 'Microsoft AI', 'MS', '#38bdf8', 'linear-gradient(135deg,#0c3a55,#061c2a)', 'rss', 'https://blogs.microsoft.com/ai/feed/'),
  ('nvidia', 'NVIDIA', 'NV', '#76b900', 'linear-gradient(135deg,#25400a,#0f1c03)', 'rss', 'https://blogs.nvidia.com/feed/'),
  ('awsml', 'AWS ML', 'AWS', '#ff9900', 'linear-gradient(135deg,#4a2f06,#201402)', 'rss', 'https://aws.amazon.com/blogs/machine-learning/feed/'),
  ('techcrunch', 'TechCrunch AI', 'TC', '#22c55e', 'linear-gradient(135deg,#0d3a1e,#051a0c)', 'rss', 'https://techcrunch.com/category/artificial-intelligence/feed/'),
  ('venturebeat', 'VentureBeat AI', 'VB', '#f97316', 'linear-gradient(135deg,#472306,#1e0e02)', 'rss', 'https://venturebeat.com/category/ai/feed/'),
  ('verge', 'The Verge AI', 'VRG', '#c084fc', 'linear-gradient(135deg,#3a1d5e,#180a2b)', 'rss', 'https://www.theverge.com/rss/ai-artificial-intelligence/index.xml'),
  ('mittr', 'MIT Tech Review', 'MIT', '#ef4444', 'linear-gradient(135deg,#4a1010,#1f0505)', 'rss', 'https://www.technologyreview.com/topic/artificial-intelligence/feed'),
  ('arstechnica', 'Ars Technica AI', 'ARS', '#fb923c', 'linear-gradient(135deg,#452508,#1d0f03)', 'rss', 'https://arstechnica.com/ai/feed/'),
  ('hn', 'Hacker News', 'HN', '#ff6600', 'linear-gradient(135deg,#4a2000,#1f0d00)', 'hn', null),
  ('devto', 'DEV Community', 'DEV', '#08090a', 'linear-gradient(135deg,#1c2740,#0a0f1c)', 'devto', null),
  ('lobsters', 'Lobsters AI', 'LOB', '#ac130d', 'linear-gradient(135deg,#3d0a07,#1a0302)', 'lobsters', null),
  ('googleresearch', 'Google Research', 'GR', '#34a853', 'linear-gradient(135deg,#0e3a22,#051d10)', 'rss', 'https://research.google/blog/rss/'),
  ('spectrum', 'IEEE Spectrum AI', 'SP', '#38bdf8', 'linear-gradient(135deg,#0c3a55,#061c2a)', 'rss', 'https://spectrum.ieee.org/feeds/topic/artificial-intelligence.rss'),
  ('mistral', 'Mistral AI', 'MIS', '#ff7000', 'linear-gradient(135deg,#4a2500,#1f0f00)', 'rss', 'https://mistral.ai/news/rss/'),
  ('apple', 'Apple ML Research', 'APL', '#a1a1aa', 'linear-gradient(135deg,#2d2d35,#101014)', 'rss', 'https://machinelearning.apple.com/rss.xml'),
  ('bair', 'BAIR', 'BAI', '#f5c518', 'linear-gradient(135deg,#4a3d05,#201a02)', 'rss', 'https://bair.berkeley.edu/blog/feed.xml'),
  ('mitnews', 'MIT News AI', 'MITN', '#ff5a36', 'linear-gradient(135deg,#4a1a0d,#200b04)', 'rss', 'https://news.mit.edu/rss/topic/artificial-intelligence2'),
  ('gradient', 'The Gradient', 'GRD', '#6ee7b7', 'linear-gradient(135deg,#0d3a2c,#051a12)', 'rss', 'https://thegradient.pub/rss/'),
  ('simonw', 'Simon Willison', 'SW', '#fbbf24', 'linear-gradient(135deg,#45330a,#1e1503)', 'rss', 'https://simonwillison.net/atom/everything/'),
  ('oneusefulthing', 'One Useful Thing', 'OUT', '#fb7185', 'linear-gradient(135deg,#43222a,#1d0c10)', 'rss', 'https://www.oneusefulthing.org/feed'),
  ('importai', 'Import AI', 'IAI', '#a78bfa', 'linear-gradient(135deg,#2e2154,#130c26)', 'rss', 'https://importai.substack.com/feed'),
  ('lillog', "Lil'Log", 'LL', '#f472b6', 'linear-gradient(135deg,#431f34,#1d0b16)', 'rss', 'https://lilianweng.github.io/index.xml'),
  ('arxiv', 'arXiv cs.AI', 'AXV', '#b91c1c', 'linear-gradient(135deg,#3f0d0d,#1a0404)', 'rss', 'https://export.arxiv.org/rss/cs.AI'),
  ('kaggle', 'Kaggle Blog', 'KGL', '#20beff', 'linear-gradient(135deg,#0c3a52,#051a25)', 'rss', 'https://medium.com/feed/kaggle-blog'),
  ('latent', 'Latent Space', 'LT', '#818cf8', 'linear-gradient(135deg,#23205e,#0f0d2b)', 'rss', 'https://www.latent.space/feed'),
  ('mlmastery', 'ML Mastery', 'MLM', '#f97316', 'linear-gradient(135deg,#4a2405,#201002)', 'rss', 'https://machinelearningmastery.com/feed/'),
  ('kdnuggets', 'KDnuggets', 'KDN', '#f8e71c', 'linear-gradient(135deg,#4a4306,#211c02)', 'rss', 'https://www.kdnuggets.com/feed'),
  ('chiphuyen', 'Chip Huyen', 'CH', '#5eead4', 'linear-gradient(135deg,#12443c,#071c18)', 'rss', 'https://huyenchip.com/feed.xml'),
  ('raschka', 'Ahead of AI', 'AAI', '#f472b6', 'linear-gradient(135deg,#43204a,#1d0b21)', 'rss', 'https://magazine.sebastianraschka.com/feed'),
  ('sequence', 'The Sequence', 'SEQ', '#4ade80', 'linear-gradient(135deg,#0f3d23,#051a0d)', 'rss', 'https://thesequence.substack.com/feed'),
  ('interconnects', 'Interconnects', 'INT', '#a78bfa', 'linear-gradient(135deg,#2e1f5e,#130c28)', 'rss', 'https://www.interconnects.ai/feed'),
  ('decoder', 'The Decoder', 'DEC', '#60a5fa', 'linear-gradient(135deg,#122c55,#071229)', 'rss', 'https://the-decoder.com/feed/'),
  ('techmeme', 'Techmeme', 'TM', '#e2e8f0', 'linear-gradient(135deg,#2d3442,#12151d)', 'rss', 'https://techmeme.com/feed.xml'),
  ('uniteai', 'Unite AI', 'UAI', '#22c55e', 'linear-gradient(135deg,#0e3a1f,#051a0c)', 'rss', 'https://www.unite.ai/feed/'),
  ('marktechpost', 'MarkTechPost', 'MTP', '#fb923c', 'linear-gradient(135deg,#452708,#1d0f03)', 'rss', 'https://www.marktechpost.com/feed/'),
  ('snorkel', 'Snorkel', 'SNK', '#7dd3fc', 'linear-gradient(135deg,#123d55,#071a26)', 'rss', 'https://snorkel.ai/feed/')
on conflict (id) do nothing;

insert into public.benchmarks (id, name, unit, higher_is_better) values
  ('swe-bench-verified', 'SWE-bench Verified', '%', true),
  ('swe-bench', 'SWE-bench', '%', true),
  ('terminal-bench', 'Terminal-Bench', '%', true),
  ('mmlu-pro', 'MMLU-Pro', '%', true),
  ('mmlu', 'MMLU', '%', true),
  ('gpqa-diamond', 'GPQA Diamond', '%', true),
  ('gpqa', 'GPQA', '%', true),
  ('humaneval', 'HumanEval', '%', true),
  ('aime', 'AIME', '%', true),
  ('math', 'MATH', '%', true),
  ('gsm8k', 'GSM8K', '%', true),
  ('arena-elo', 'Arena Elo', 'elo', true),
  ('livebench', 'LiveBench', '%', true),
  ('hellaswag', 'HellaSwag', '%', true),
  ('winogrande', 'WinoGrande', '%', true),
  ('imagenet', 'ImageNet', '%', true),
  ('gaia', 'GAIA', '%', true),
  ('webarena', 'WebArena', '%', true),
  ('bigbench', 'BigBench', '%', true),
  ('arc-agi', 'ARC-AGI', '%', true)
on conflict (id) do nothing;
